### PR TITLE
Uses a real go project to showcase vendor example so glide works

### PR DESCRIPTION
**Pull request by vishal-biyani**
The issue for this PR is explained in #823 

Right now a standard go lang project is used but I am ok with creating a small simple Go project in Fission repo and then use that as a dependency for Go vendor example. As long as the project used resolves to an appropriate path by glide - it works. 

@life1347 Do you mind taking a look at this please.

---
This change is [Reviewable](https://reviewable.io/reviews/fission/fission/828)

### CODE REVIEW

**Comment by life1347** [comment]
Ooops, sorry I didn't know that will break `glide up -v`.
I think its good idea to add a real go dependency and make it more realistic, let's keep it. But since its a dependency for example,  I suggest adding following lines into `glide.yaml` to avoid adding the unnecessary dependencies in `glide.yaml`.

```
excludeDirs:
- examples
- hack
- test
```

**Comment by vishal-biyani** [comment]
I tried `excludeDirs` but that could not fix Glide issue. I will check once more if I made some mistake in adding that and confirm here.

**Comment by life1347** [comment]
I tested with glide version: 10.3.1

```
# glide.yaml
package: github.com/fission/fission
excludeDirs:
- examples
- hack
- test
import:
...
```

### Before adding
```
[WARN]	Unable to checkout go/vendordir/test
[ERROR]	Error looking for go/vendordir/test: Cannot detect VCS
...
[ERROR]	Failed to retrieve a list of dependencies: Error resolving imports
```

### After
`glide up -v` without error.

**Comment by vishal-biyani** [comment]
I will update this PR and close other one.

**Comment by vishal-biyani** [comment]
@life1347 updated the PR with `excludeDirs` added

**Comment by life1347** [comment]
LGTM

**Pull request merged**
