### PR TITLE
Removed the fn pods functionality

### LINKED ISSUE #590: Remove `fission fn pods` command
It's not particularly useful.

### PR DESCRIPTION
**Pull request by vishal-biyani**
Fixes #590 and related to #592

---
This change is [Reviewable](https://reviewable.io/reviews/fission/fission/594)

### CODE REVIEW

**Comment by life1347** [comment]
The reason I add `deprecated` is to notify users that we are gonna remove the command. Just wonder should we give users some time to update their own scripts (if they have)?

**Comment by vishal-biyani** [comment]
@life1347 Sure, we can keep this PR as it is and merge when we are ready.

**Comment by life1347** [comment]
Hey, @vishal-biyani ,  would you mind rebasing on master? Then we can merge this PR once it's done.

**Comment by life1347** [comment]
LGTM!

**Pull request merged**
