### PR TITLE
Recorder CRD, Records API, Redis deployment

### PR DESCRIPTION
**Pull request by Amusement**
Notes:
* Everything is currently done in the default namespace; scoping recorders by namespace is a TODO item
* Better validation is needed in multiple places 
* The changes in router/router.go involving env variables "ROUTER_ROUND_TRIP_TIMEOUT" et al. should be ignored

For a summary of other acknowledged issues, refer to: https://github.com/fission/fission/labels/record-replay

---
This change is [Reviewable](https://reviewable.io/reviews/fission/fission/818)

### CODE REVIEW

**Comment by smruthi2187** [comment]
I've only reviewed the router/recorder.go and router/httpTriggers.go for now. Please address these comments while I get back to reviewing the other files. Thanks.

**Comment by smruthi2187** [comment]
LGTM. Feel free to address review comments or make TODOs.
In the meanwhile, i'll work on your glide issues and get back to you soon.

**Comment by smruthi2187** [comment]
*[a discussion](https://reviewable.io/reviews/fission/fission/818#-LIQxwo17m5NJjbpAjCW:-LJ-y8Dj88g9HuWnx5sd:b-li9d8k) (no related file):*
<details><summary><i>Previously, smruthi2187 wrote…</i></summary><blockquote>

typo above : commits -> imports. sorry.
</blockquote></details>

Also, had one more general comment. log.Fatal can be replaced with log.Error and return. We could let the caller take care of handling retries or take some action based on the error.

---

**Comment by life1347** [comment]
___
*[redis/redis.go, line 42 at r4](https://reviewable.io/reviews/fission/fission/818#-LJCZKee2IyDbSCS5mIc:-LJCZKee2IyDbSCS5mId:b-58ewks) ([raw file](https://github.com/fission/fission/blob/dbe167e6f98f7d241037224591ec76541933972c/redis/redis.go#L42)):*
> ```Go
> 	escPayload := string(json.RawMessage(payload))
> 
> 	client := NewClient()
> ```

Add `redis.Conn` as parameter of function instead of creating new client here, and also for other functions that need to connect to redis.
It's really useful for doing dependency injection when unit test.
```
func EndRecord(redis redis.Conn, triggerName string, .....
```

**Comment by life1347** [comment]
___
*[fission/main.go, line 304 at r4](https://reviewable.io/reviews/fission/fission/818#-LJCwI2d8dvhnyNDZEyx:-LJCwI2d8dvhnyNDZEyy:b4044ed) ([raw file](https://github.com/fission/fission/blob/dbe167e6f98f7d241037224591ec76541933972c/fission/main.go#L304)):*
> ```Go
> 		{Name: "timetrigger", Aliases: []string{"tt", "timer"}, Usage: "Manage Time triggers (timers) for functions", Subcommands: ttSubcommands},
> 		{Name: "mqtrigger", Aliases: []string{"mqt", "messagequeue"}, Usage: "Manage message queue triggers for functions", Subcommands: mqtSubcommands},
> 		{Name: "recorder", Usage: "Manage recorders for functions", Subcommands: recSubcommands, Hidden: true},
> ```

Didn't know about `Hidden`, cool!

**Comment by life1347** [comment]
Some comments above ^. And, don't forget to rebase the latest master branch.

**Comment by life1347** [comment]
LGTM. Merged 🎉 🎉 🎉

**Pull request merged**
