### PR TITLE
Vadasambar configurable newdeploy timeout

### PR DESCRIPTION
**Pull request by life1347**
CI builds for #1260

---
This change is [Reviewable](https://reviewable.io/reviews/fission/fission/1267)

### CODE REVIEW

**Comment by vadasambar** [comment]
@life1347 , what is this PR for?

**Comment by life1347** [comment]
@vadasambar The CI build for the PR external contributor opened only runs the basic unit tests and static check. So this PR is to trigger CI build with kubernetes integration test, once it passed we will close this one and merge yours.

**Comment by vadasambar** [comment]
@life1347 ahhhh! Thank you :)

**Comment by vadasambar** [comment]
I think we can run integrations tests again. I have applied the diff which comments out specializationtimeout validation.

**Comment by life1347** [comment]
CI build result: https://travis-ci.org/fission/fission/builds/571724467

**Pull request closed without merging**
