### PR TITLE
Golang v2 environment -- runtime and builder

### PR DESCRIPTION
**Pull request by soamvasani**
A v2 environment for Go. 

Needs better error checking and a README update, but other that it works.

---
This change is [Reviewable](https://reviewable.io/reviews/fission/fission/427)

### CODE REVIEW

**Comment by soamvasani** [comment]
@life1347 @erwinvaneyk comments welcome

**Comment by erwinvaneyk** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[environments/go/Dockerfile, line 1 at r1](https://reviewable.io:443/reviews/fission/fission/427#-L-fCJ_uxGnst_wQWWou:-L-fCJ_uxGnst_wQWWov:b-57jvu5) ([raw file](https://github.com/fission/fission/blob/e5f4e46e1cb8fadbbb58fcbb5983398287a151a2/environments/go/Dockerfile#L1)):*
> ```Dockerfile
> FROM golang:1.9.2
> ```

You might want to use a buildarg for the golang version and default to 1.9.2

---

*[environments/go/server.go, line 111 at r1](https://reviewable.io:443/reviews/fission/fission/427#-L-fFdQstMt7WVsL9fx4:-L-fFdQstMt7WVsL9fx5:bzdjos9) ([raw file](https://github.com/fission/fission/blob/e5f4e46e1cb8fadbbb58fcbb5983398287a151a2/environments/go/server.go#L111)):*
> ```Go
> func specializeHandlerV2(w http.ResponseWriter, r *http.Request) {
> 	if userFunc != nil {
> 		w.WriteHeader(400)
> ```

`http.StatusBadRequest`

---

*[environments/go/builder/build.sh, line 3 at r1](https://reviewable.io:443/reviews/fission/fission/427#-L-fEnYgCBxVCQ4BUgIU:-L-fEnYgCBxVCQ4BUgIV:b-1ot8yd) ([raw file](https://github.com/fission/fission/blob/e5f4e46e1cb8fadbbb58fcbb5983398287a151a2/environments/go/builder/build.sh#L3)):*
> ```Shell
> #!/bin/sh
> 
> go build -buildmode=plugin -o ${DEPLOY_PKG} ${SRC_PKG}
> ```

Haven't checked this, but shouldn't this have envs added to ensure that the build is for Linux?

---

*[environments/go/builder/Dockerfile, line 4 at r1](https://reviewable.io:443/reviews/fission/fission/427#-L-fDMSJDp9tywpl17PU:-L-fDMSJDp9tywpl17PV:bvt25xx) ([raw file](https://github.com/fission/fission/blob/e5f4e46e1cb8fadbbb58fcbb5983398287a151a2/environments/go/builder/Dockerfile#L4)):*
> ```Dockerfile
> FROM ${BUILDER_IMAGE}
> 
> FROM golang:1.9.2
> ```

Same here, propose making the golang version also a buildarg.

Btw cool use of  the multistage docker build :grin: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fission/fission/427)*

**Comment by erwinvaneyk** [comment]
*[environments/go/builder/build.sh, line 3 at r1](https://reviewable.io:443/reviews/fission/fission/427#-L-fEnYgCBxVCQ4BUgIU:-L-fIRI2cs-44OOG9P7g:b4ay9v7) ([raw file](https://github.com/fission/fission/blob/e5f4e46e1cb8fadbbb58fcbb5983398287a151a2/environments/go/builder/build.sh#L3)):*
<details><summary><i>Previously, erwinvaneyk (Erwin van Eyk) wrote…</i></summary><blockquote>

Haven't checked this, but shouldn't this have envs added to ensure that the build is for Linux?
</blockquote></details>

Nvm brainfart -- this is executed inside the builder container

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fission/fission/427)*

**Comment by soamvasani** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[environments/go/Dockerfile, line 1 at r1](https://reviewable.io:443/reviews/fission/fission/427#-L-fCJ_uxGnst_wQWWou:-L-j4SaGgCn2tF_M-cg2:b-896fix) ([raw file](https://github.com/fission/fission/blob/e5f4e46e1cb8fadbbb58fcbb5983398287a151a2/environments/go/Dockerfile#L1)):*
<details><summary><i>Previously, erwinvaneyk (Erwin van Eyk) wrote…</i></summary><blockquote>

You might want to use a buildarg for the golang version and default to 1.9.2
</blockquote></details>

Done.

---

*[environments/go/server.go, line 111 at r1](https://reviewable.io:443/reviews/fission/fission/427#-L-fFdQstMt7WVsL9fx4:-L-j4TZ_--LQvADdDc_w:b-896fix) ([raw file](https://github.com/fission/fission/blob/e5f4e46e1cb8fadbbb58fcbb5983398287a151a2/environments/go/server.go#L111)):*
<details><summary><i>Previously, erwinvaneyk (Erwin van Eyk) wrote…</i></summary><blockquote>

`http.StatusBadRequest`
</blockquote></details>

Done.

---

*[environments/go/builder/build.sh, line 3 at r1](https://reviewable.io:443/reviews/fission/fission/427#-L-fEnYgCBxVCQ4BUgIU:-L-j4UPO0AMjCba4pQ8Y:b-896fix) ([raw file](https://github.com/fission/fission/blob/e5f4e46e1cb8fadbbb58fcbb5983398287a151a2/environments/go/builder/build.sh#L3)):*
<details><summary><i>Previously, erwinvaneyk (Erwin van Eyk) wrote…</i></summary><blockquote>

Nvm brainfart -- this is executed inside the builder container
</blockquote></details>

Done.

---

*[environments/go/builder/Dockerfile, line 4 at r1](https://reviewable.io:443/reviews/fission/fission/427#-L-fDMSJDp9tywpl17PU:-L-j4V7f4Wb5gOrubSS1:b-896fix) ([raw file](https://github.com/fission/fission/blob/e5f4e46e1cb8fadbbb58fcbb5983398287a151a2/environments/go/builder/Dockerfile#L4)):*
<details><summary><i>Previously, erwinvaneyk (Erwin van Eyk) wrote…</i></summary><blockquote>

Same here, propose making the golang version also a buildarg.

Btw cool use of  the multistage docker build :grin: 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fission/fission/427)*

**Pull request merged**
