### PR TITLE
Fix router panic when trying to update route

### PR DESCRIPTION
**Pull request by life1347**
### Description
This PR aims to solve the issue #810 . The root cause is the size of `ts.triggers` changed when multiple go-routine called `ts.syncTriggers()`. 

https://github.com/fission/fission/blob/d11ab717076ef8c9911d887383ad41809ef1efb6/router/httpTriggers.go#L109-L111

### Solution
There are two ways to solve the problem:

1. Pass triggers & functions slice to `ts.getRouter()`
This solution will encounter another problem when the router under heavy load. Since we cannot make sure when will a go-routine was brought up to execute. The slice may contain old slices of triggers & functions.

2. Use the unbuffered channel to ensure the update sequence
This solution ensures that there is at most one call to update `ts.triggers` and `ts.functions`, thus that we can avoid the index out of range problem.

Conclusion: Use solution 2.

---
This change is [Reviewable](https://reviewable.io/reviews/fission/fission/811)

### CODE REVIEW

**Comment by germancho14** [comment]
I wonder why ts.triggers and ts.functions are needed when we could just get the triggers and functions from the ts.triggerStore and ts.functionStore directly on the getRouter function. It seems that the stores are thread-safe, so the extra channel wouldn't be needed.

**Comment by life1347** [comment]
Yeah, I also noticed that `ts.triggers` & `ts.functions` are not necessary at first glance. But after digging into the source code, notice that its necessary for unit test to do dependencies injection.
https://github.com/fission/fission/blob/ec495fbd1d5b10c4f04bab63a61f62d07c34c3e5/router/router_test.go#L70
If getRouter rely on triggerStore, then it will not be able to set routes during the unit test.

**Comment by germancho14** [comment]
I also so that. Perhaps the store can be mocked for the purpose of unit testing. 
I changed the code to use the store directly and it works. I am creating lots of different functions and routes in a short time span. The change seems to be working at first glance.

**Comment by life1347** [comment]
I personally think the extra benefit of a channel that it helps to reduce the active `update route` go-routine since most of the go-routine are waiting to execute. Since `latestTriggers := ts.triggerStore.List()` always get the latest objects from the store, we don't really lots of `update` go-routine in active state simultaneously.

For the test part, maybe we can mock the store but it also makes the test and changes more complicated.

**Comment by germancho14** [comment]
Wouldn't the amount of work be the same if you are pushing on a channel in ResourceEventHandlerFuncs or just update the router directly using the stores?  I think the important thing here is that when modifying the router routers it should be thread-safe. If you are using ts.triggers and ts.functions you can use a channel (your solution), or use a thread-safe store (what I suggest).  

Perhaps your approach would be better since there would be lots of contention happening on the store using the approach I suggest. With your approach there wouldn't be any contention (process one thing at a time).

**Comment by smruthi2187** [comment]
LGTM!

**Pull request merged**
