### PR TITLE
Added ability to update resources through cli

### LINKED ISSUE #1721: Ability to update fission env variables through fission CLI
**Is your feature request related to a problem? Please describe.**
Missing functionality to update min/max cpu/mem of an exiting ENV. Currently, to update, we are forced to delete and re-create the env. This also has a risk of dependent functions being erratic. It also de-couple resource utilization independent of function creation and be useful to update the resource in a quick to respond situation without affecting the functions.

**Describe the solution you'd like**
Ability to update resources like min/max cpu/mem of an env through fission cli `fission env update`

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by Divya063**
Closes #1721 There is one problem, using the command `fission env list` doesn't show the updated values.

---
This change is [Reviewable](https://reviewable.io/reviews/fission/fission/1800)

### CODE REVIEW

**Review by andria247 — APPROVED** [review]

**Review by therahulbhati — CHANGES_REQUESTED** [review]
@Divya063 Can you please add `XPreserveUnknownFields: boolPtr(true)` in the https://github.com/fission/fission/blob/ec22e22bbdf5c766eaee0220c648438039629376/pkg/crd/crdvalidations.go#L89

**Comment by vishal-biyani** [comment]
Hi @Divya063 Do you plan to make suggested changes? 
Hey @therahulbhati Is this still relevant?

**Comment by Divya063** [comment]
@vishal-biyani This was already done in PR #1833

**Comment by vishal-biyani** [comment]
Thank you for confirming @Divya063 I will close this one.

**Pull request closed without merging**
