### PR TITLE
Implement support for Azure storage message queue triggers

### PR DESCRIPTION
**Pull request by peterhuene**
These commits implement support for consuming messages from an Azure storage queue to trigger Fission functions.

Implemented:

* Helm chart modified to allow the MQTM to be configured for consuming Azure storage queues instead of NATS (see updated README for details).
* Modified the MQTM to support the `azure-storage-queue` option.
* Implemented a message queue provider that consumes messages from an Azure storage queue.
    * Automatic retry (up to three attempts currently) implemented for failed invocations.
    * Automatic moving of messages causing failure to a "poison" queue; this is similar to what Azure Functions does for failed messages.
* Added a root Makefile with the following targets:
    * `test` - Runs all tests in the repo.
    * `build` - Builds both the client and server (bundle) binaries.
    * `install` - Installs the client binary into the Go bin path.
    * `image` - Builds the server (bundle) image.
    * `image-push` - Pushes the current server (bundle) image.
* Added extensive unit tests for the Azure storage message queue provider that use testify's mocking framework to mock interactions with Azure and with triggered functions.

---
This change is [Reviewable](https://reviewable.io/reviews/fission/fission/371)

### CODE REVIEW

**Comment by peterhuene** [comment]
Hi @soamvasani,

Thanks for taking the time for conferencing with us a few weeks ago.  As promised, here is some work to trigger Fission functions based on Azure storage queue messages.

This was the work of @jsturtevant and myself.  Given that you didn't request this feature and it was just something we hacked on together, we don't have expectations that this be merged unless it is desired functionality that aligns with Fission's goals.

We'll be around to quickly make amends to the commits if there is feedback that needs to be addressed.

Thanks again!

**Comment by soamvasani** [comment]
Thanks @peterhuene and @jsturtevant ! Looks like you did quite a lot of work, appreciate the attention to tests and build system too! :)

It is certainly in line with our goals to have this integration. I'll take a look at this over the next couple of days.

**Comment by soamvasani** [comment]
Hey @peterhuene @jsturtevant my apologies for not getting to this for a while. Since the master branch has changed quite a bit since then, @life1347 is going to work on rebasing this to master on a new PR.

**Comment by peterhuene** [comment]
Thanks, @soamvasani!  I'd be happy to rebase this PR if needed, too.  Just let me know.

**Comment by soamvasani** [comment]
Hey @peterhuene thanks, that'd be great! 

@life1347, please review and merge when it's ready.

**Comment by peterhuene** [comment]
Hi @soamvasani and @life1347:

Sorry for the delay.  I've rebased on master and pushed up the changes.

Please let me know if there are any problems; I'll respond to code review feedback when I'm able.

Thanks!

**Comment by peterhuene** [comment]
Looks like the tests failed because I think I was stripping vendor directories when I updated glide.lock (i.e. `glide get -v foo`) and had no problems building or running tests as a result.  However, this is not the way Travis is installing glide dependencies (`glide install` without `-v`).

What's the recommended way to update `glide.lock` that you use?  I'll try to amend the two commits that update `glide.lock` using the preferred way.

Thanks!

**Comment by soamvasani** [comment]
Thanks @peterhuene ! I didn't know about `glide install -v`.  @life1347 is adding it in #480, does that solve the build problem?

**Comment by life1347** [comment]
I've tested locally, it should solve the build problem. Just let me know if you still meet the build problem :)

**Comment by peterhuene** [comment]
@life1347 Thanks! I've pushed with a rebase, so hopefully this will go green and ready for review.

**Comment by soamvasani** [comment]
Merged glide.lock conflicts; integration tests on the [pr371-copy](https://travis-ci.org/fission/fission/builds/339336883) branch passed.

**Comment by peterhuene** [comment]
I'll rebase if you'd like this PR updated :)

**Comment by soamvasani** [comment]
I'm going to merge this now, it looks pretty good!  The version in the Makefile is outdated but let's fix that later, don't want to drag this out further.  The function failure behavior here is nicely designed (retry limit + poison queue), we should copy this pattern over to the NATS trigger as well :)

@peterhuene: if you have the time, it would be really great to have a howto/usage tutorial somewhere under /Documentation/docs-site -- that site gets rendered to http://fission.io/docs

**Comment by soamvasani** [comment]
🎉  Thanks again for the contributions, @peterhuene and @jsturtevant !

**Comment by peterhuene** [comment]
You're quite welcome!  Thanks for meeting with us back in October and reviewing our work!

I'd be happy to make a docs contribution when I get some spare time.  I'll try to set aside some time next week for it.

**Pull request merged**
