### PR TITLE
Fix case of GitHub

### PR DESCRIPTION
**Pull request by jbampton**
This change is [Reviewable](https://reviewable.io/reviews/fission/fission/1768)

### CODE REVIEW

**Comment by jbampton** [comment]
Why did you close this down @vishal-biyani  ?

**Comment by vishal-biyani** [comment]
Hey @jbampton I am sorry, I got a bunch of spam PRs, and I mistakenly closed this too!

**Comment by jbampton** [comment]
Hey @vishal-biyani can you please remove the `invalid` label ?

Would love it if you merged this one 👍

**Comment by vishal-biyani** [comment]
This has been fixed in another doc PR covering all docs. Thanks.

**Pull request closed without merging**
