### PR TITLE
[skip ci] fix contributing.md link on readme

### PR DESCRIPTION
**Pull request by mrturkmencom**
This change is [Reviewable](https://reviewable.io/reviews/fission/fission/1731)

### CODE REVIEW

**Comment by vishal-biyani** [comment]
Thanks a lot @mrturkmencom - I can't seem to get Travis to make it green, but let me fix that

**Comment by mrturkmencom** [comment]
Since commit message includes [skip ci], it prevents travis to run tests. Ok, I can amend the commit message. @vishal-biyani

**Comment by mrturkmencom** [comment]
Yeah, now it should be ok.

**Comment by chetanpdeshmukh** [comment]
Hello @mrturkmencom ,
Thanks again for the PR!

Thank you for contributing to Fission project. Could you please fill out [this form](https://docs.google.com/forms/d/e/1FAIpQLSdhxtWL5N2PU7MYC2IRRAzYw-CrG9QtsYNvkiiOPVEQj8i51w/viewform?usp=sf_link), so we can send you the well deserved awesome swags :)

Team Fission

**Pull request merged**
