### PR TITLE
Provide secrets and configmaps while updating the functions

### LINKED ISSUE #1357: Ability to update secret&configmap with fn update
We should be able to update the secret&configmap through `fn update`
```
fission fn update --name xxx --secret yyy
```

### PR DESCRIPTION
**Pull request by viveksinghggits**
this change fixes #1357

---
This change is [Reviewable](https://reviewable.io/reviews/fission/fission/1358)

### CODE REVIEW

**Comment by viveksinghggits** [comment]
Hi @life1347 ,
do I have to update the test cases as well. I didnt see test cases for `fn update` .

**Comment by life1347** [comment]
@viveksinghggits Kind of busy this week. I will give it a test before the weekend. But so far I think it looks good to me.

**Comment by life1347** [comment]
I'm surprised that we did support to update the secret and configmap but didn't add flags to the command. LGTM! After addressing the conflict, we are good to go.

**Comment by viveksinghggits** [comment]
yes, It wasnt a big change.

**Comment by life1347** [comment]
Hey @viveksinghggits any updates to this PR?

**Comment by viveksinghggits** [comment]
Hi @life1347,
Can you please review it once again.

**Comment by life1347** [comment]
LGTM!  👍

**Pull request merged**
