### PR TITLE
changes made to FluentD configuration to circumvent Logger daemonset

### PR DESCRIPTION
**Pull request by prithviramesh**
Have to check what is stored in InfluxDB and if the function name is query-able

---
This change is [Reviewable](https://reviewable.io/reviews/fission/fission/380)

### CODE REVIEW

**Comment by soamvasani** [comment]
Thanks @prithviramesh! 

Can you check on the build failure?

Also, can you take a look at the tests in /test/tests/, and add a logging test there?

**Comment by prithviramesh** [comment]
Sure thing @soamvasani

**Comment by soamvasani** [comment]
Reviewed 3 of 6 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[charts/fission-all/values.yaml, line 13 at r2](https://reviewable.io:443/reviews/fission/fission/380#-KxnnPjaMWf5KVxXd1AI:-KxnnPjcMROLF1dfpSty:b6qctgp) ([raw file](https://github.com/fission/fission/blob/b92f183f789ab96f10f4ddbfe8e1e2ea9ee2aa90/charts/fission-all/values.yaml#L13)):*
> ```YAML
> 
> ## Image pull policy
> pullPolicy: Always
> ```

Please don't change this default. You can always override it in your own testing using the helm commandline.

---

*[charts/fission-all/values.yaml, line 47 at r2](https://reviewable.io:443/reviews/fission/fission/380#-KxnnWMrTmjvtdOQuXDB:-KxnnWMrTmjvtdOQuXDC:bbm342x) ([raw file](https://github.com/fission/fission/blob/b92f183f789ab96f10f4ddbfe8e1e2ea9ee2aa90/charts/fission-all/values.yaml#L47)):*
> ```YAML
> logger:
>   influxdbAdmin: "admin"
>   fluentdImage: pvramesh/fluentd:flat
> ```

I assume this is included in the PR by mistake, but in case it's not, please remove it so we can ship the fluentd image from fission's repo.

---

*[charts/fission-all/templates/deployment.yaml, line 444 at r2](https://reviewable.io:443/reviews/fission/fission/380#-Kxno1Qpn7AUjmTBnynR:-Kxno1Qpn7AUjmTBnynS:bdk7ku9) ([raw file](https://github.com/fission/fission/blob/b92f183f789ab96f10f4ddbfe8e1e2ea9ee2aa90/charts/fission-all/templates/deployment.yaml#L444)):*
> ```YAML
>           volumeMounts:
>             - name: container-log
>               mountPath: /var/log/
> ```

Why is this needed?

---

*[charts/fission-all/templates/deployment.yaml, line 456 at r2](https://reviewable.io:443/reviews/fission/fission/380#-Kxno7ESW-xp5ePniMqr:-Kxno7ETqA3_D5bLbUT5:b-e781rd) ([raw file](https://github.com/fission/fission/blob/b92f183f789ab96f10f4ddbfe8e1e2ea9ee2aa90/charts/fission-all/templates/deployment.yaml#L456)):*
> ```YAML
>         - name: container-log
>           hostPath:
>               path: /var/log/
> ```

Same question, why is this needed?

---

*[fission/logdb/influxdb.go, line 101 at r2](https://reviewable.io:443/reviews/fission/fission/380#-KxnoHf6FyrAMeVbvKLD:-KxnoHf6FyrAMeVbvKLE:bt6sgn7) ([raw file](https://github.com/fission/fission/blob/b92f183f789ab96f10f4ddbfe8e1e2ea9ee2aa90/fission/logdb/influxdb.go#L101)):*
> ```Go
> 					Timestamp: t,
> 					Container: row[2].(string),
> 					FuncName:  row[8].(string),
> ```

This function deserves an explanatory comment

---

*[logger/fluentd/build.sh, line 2 at r2](https://reviewable.io:443/reviews/fission/fission/380#-KxnoLjEJfdqiQvFQna1:-KxnoLjEJfdqiQvFQna2:b-6b3mcx) ([raw file](https://github.com/fission/fission/blob/b92f183f789ab96f10f4ddbfe8e1e2ea9ee2aa90/logger/fluentd/build.sh#L2)):*
> ```Shell
> #!/bin/sh
> docker build -t pvramesh/fluentd:latest  .
> ```

Again, I assume this is included by mistake, please remove

---

*[logger/fluentd/fluent.conf, line 9 at r2](https://reviewable.io:443/reviews/fission/fission/380#-KxnoVJ-6yQU9pK0BUsM:-KxnoVJ0yNqULDtx3Unx:b-rbb65d) ([raw file](https://github.com/fission/fission/blob/b92f183f789ab96f10f4ddbfe8e1e2ea9ee2aa90/logger/fluentd/fluent.conf#L9)):*
> ```
>   format json 
>   time_key time
>   path /var/log/containers/*fission-function*.log
> ```

Unfortunately, you can't hard code the value "fission-function" because this is a namespace that's user-configurable. And it does not look like this config file allows you to specify an environment var or anything like that here?

So you'll have to generate this file using a script and then invoke fluentd on it. We can discuss this design further.

---

*[test/tests/test_logging/test_function_logs.sh, line 39 at r2](https://reviewable.io:443/reviews/fission/fission/380#-Kxnq-z56NXjV2a6s1dt:-Kxnq-z56NXjV2a6s1du:b-4ra423) ([raw file](https://github.com/fission/fission/blob/b92f183f789ab96f10f4ddbfe8e1e2ea9ee2aa90/test/tests/test_logging/test_function_logs.sh#L39)):*
> ```Shell
> 
> logs=$(fission function logs --name $fn -d)
> echo "$logs"
> ```

You need to make the test fail if/when the logs are missing. So something like "num=$(echo $logs | grep 'log test' | wc -l)" and then ensure that num == 4. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fission/fission/380)*

**Comment by prithviramesh** [comment]
Thanks for your comments @soamvasani, I'll make the necessary changes

**Comment by prithviramesh** [comment]
@soamvasani /var/log/ is needed as the volume mount because of the symlinks between /var/log/containers/ and /var/log/pods. Otherwise I get the same exact error mentioned here https://github.com/fabric8io/docker-fluentd-kubernetes/issues/14

**Comment by soamvasani** [comment]
Reviewed 4 of 6 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[charts/fission-all/templates/deployment.yaml, line 351 at r4](https://reviewable.io:443/reviews/fission/fission/380#-KyNYRVfnw0kc5Q8go1Y:-KyNYRVgoM2F1ZzJoxKC:b-75ywm7) ([raw file](https://github.com/fission/fission/blob/2729b12ed5068a60802582b057ec7de19e0e9726/charts/fission-all/templates/deployment.yaml#L351)):*
> ```YAML
>     chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
> spec:
>   type: NodePort 
> ```

why is this needed?

---

*[logger/fluentd/build.sh, line 2 at r4](https://reviewable.io:443/reviews/fission/fission/380#-KyNZdA4n1RMgEvQn7it:-KyNZdA4n1RMgEvQn7iu:b-rv7d4k) ([raw file](https://github.com/fission/fission/blob/2729b12ed5068a60802582b057ec7de19e0e9726/logger/fluentd/build.sh#L2)):*
> ```Shell
> #!/bin/sh
> docker build -t fission-daemonset-fluentd:latest . --no-cache
> ```

Can you remove the --no-cache? Doesn't seem necessary?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fission/fission/380)*

**Comment by soamvasani** [comment]
Looks great overall! 

We might as well remove the logger and remove the call into the logger from poolmgr/gp.go.

---

Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[charts/fission-all/templates/deployment.yaml, line 403 at r5](https://reviewable.io:443/reviews/fission/fission/380#-KyS4neDRGCipjhO5dx7:-KyS4neEos1P2v-ZZZ40:b-56rqrk) ([raw file](https://github.com/fission/fission/blob/4f2cae9caa21186d1f663e281c4e8736542a919b/charts/fission-all/templates/deployment.yaml#L403)):*
> ```YAML
>     spec:
>       containers:
>         - name: logger
> ```

We can remove this whole container now, right? And we can also delete the logger code from the repo.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fission/fission/380#-:-KyS5-PXlxPLKS8ajxq-:b-w5bavn)*

**Comment by soamvasani** [comment]
LGTM

---

Reviewed 7 of 7 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fission/fission/380#-:-KywuB3GXcx1dDcu_4RP:bb6ywmx)*

**Pull request merged**
