### PR TITLE
Updates required for multi-architecture builds.

### PR DESCRIPTION
**Pull request by cerebrate**
This PR adds support and documentation for multi-architecture builds for Fission itself using `docker buildx` as per the conversation in #1421 , which this should close.

A parallel PR for the environments repo should follow shortly.

---
This change is [Reviewable](https://reviewable.io/reviews/fission/fission/1891)

### CODE REVIEW

**Comment by cerebrate** [comment]
Oops. I noticed that preupgradechecks was also in this repo, even if not built by the main makefile. I added a commit modding its dockerfile to allow multi-arch building too.

**Comment by vishal-biyani** [comment]
Thanks a lot @cerebrate - will take a look post holidays.

**Review by RealHarshThakur — APPROVED** [review]

**Review by RealHarshThakur — CHANGES_REQUESTED** [review]
@cerebrate can you please add the `docker buildx` command for preupgrade checks too?

**Comment by cerebrate** [comment]
@RealHarshThakur It not being build by the main Makefile - by that do you mean add it in test/test_utils.sh, and if so, should I update the commands there to build the various other images too?

(Except presumably the environments, since they're being moved to fission/environments anyway?)

**Comment by RealHarshThakur** [comment]
I just meant to add the command in the main Makefile under multiarch-image .

**Comment by cerebrate** [comment]
Oh! Sorry, that's done now.

**Review by RealHarshThakur — APPROVED** [review]

**Comment by RealHarshThakur** [comment]
Thanks a lot @cerebrate for the PR :)

**Comment by vishal-biyani** [comment]
Thanks for this PR @cerebrate 

@RealHarshThakur While with this PR we can build multi-arch images, we will have to make changes to the release script separately still. Can you please raise a PR for that?

**Comment by RealHarshThakur** [comment]
Sure

**Comment by richburdon** [comment]
Hi folks -- I'm installing fission for the first time. Via Ubuntu running on ARM.

I can't find any docs to get around the error when running fission after:

```
sudo kubectl apply -f https://github.com/fission/fission/releases/download/v1.18.0/fission-all-v1.18.0.yaml
```

Error:

```
`-bash: /usr/local/bin/fission: cannot execute binary file: Exec format error`
```

**Pull request merged**
