### PR TITLE
Fix timer and executor bugs

### PR DESCRIPTION
**Pull request by gw123**
## Which issue(s) this PR fixes:

Fixes #

## Checklist:

- [ ] I ran tests as well as code linting locally to verify my changes. 
- [ ] I have done manual verification of my changes, changes working as expected.
- [ ] I have added new tests to cover my changes.
- [ ] My changes follow contributing guidelines of Fission.
- [ ] I have signed all of my commits.

### CODE REVIEW

**Comment by gw123** [comment]
sometimes router executor will crash,

I found several places in the code that didn't check for null pointers, I fixed some based on my usage.

**Comment by sanketsudake** [comment]
Hey @gw123 ,

Thanks for identifying fixes in the PR.
This PR has lot of fixes, could you break down PR into multiple ones depending upon issue and resolution it is trying to do.

Also generally I think we should avoid recover from panic code as fix. We should identify what caused panic and fix.

I am also looking into fixes in the PR and seeing what could be merged in the PR.

**Comment by sanketsudake** [comment]
Hey @gw123 ,

Thanks for identifying fixes in the PR.
This PR has lot of fixes, could you break down PR into multiple ones depending upon issue and resolution it is trying to do.

Also generally I think we should avoid recover from panic code as fix. We should identify what caused panic and fix.

I am also looking into fixes in the PR and seeing what could be merged in the PR.

**Comment by sanketsudake** [comment]
I have added fix tapService here https://github.com/fission/fission/pull/2402 for issue https://github.com/fission/fission/issues/2366 .

**Comment by gw123** [comment]
thanks ,i will try it

**Comment by blackfly19** [comment]
Hi @gw123 . Are you still working on splitting the PR according to issues?

**Comment by sanketsudake** [comment]
Hi @gw123 , Closing this PR for now. Kindly raise PR as suggested in comment https://github.com/fission/fission/pull/2400#issuecomment-1088983071

**Pull request closed without merging**
