### PR TITLE
Use a separate controller loop to watch functions change and create a service

### PR DESCRIPTION
**Pull request by life1347**
This aims to solve issue #515

---
This change is [Reviewable](https://reviewable.io/reviews/fission/fission/544)

### CODE REVIEW

**Comment by smruthi2187** [comment]
LGTM. Just one question, is there a reason why the ListWatch is not part of poolmgr?
The reason I ask is if controller process is removed from fission in the future, we may have to migrate the ListWatch to poolmgr.

**Comment by life1347** [comment]
Good question! I didn't think of that before. I will push a change for moving ListWatch to poolmgr.

**Comment by soamvasani** [comment]
LGTM.

**Comment by soamvasani** [comment]
Looks like the tests failed with an executor crash:

```
2018/03/31 09:52:26 Creating NewDeploy ExecutorType
2018/03/31 09:52:26 starting executor at port 8888
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13610fa]
goroutine 24 [running]:
github.com/fission/fission/executor/poolmgr.(*GenericPoolManager).Run(0xc420381f20, 0x20dbba0, 0xc420584d80)
	src/github.com/fission/fission/executor/poolmgr/gpm.go:104 +0x3a
github.com/fission/fission/executor.(*Executor).Serve(0xc420584c00, 0x22b8)
	src/github.com/fission/fission/executor/api.go:114 +0x52a
created by github.com/fission/fission/executor.StartExecutor
	src/github.com/fission/fission/executor/executor.go:218 +0x2e6

```

**Pull request merged**
