### PR TITLE
Switch from ThirdPartyResources to CustomResourceDefinitions

### PR DESCRIPTION
**Pull request by life1347**
This PR aims to switch TPR to CRD for future kubernetes release. (https://github.com/fission/fission/issues/314)
Documentation for migration will be pushed later.

---
This change is [Reviewable](https://reviewable.io/reviews/fission/fission/381)

### CODE REVIEW

**Comment by soamvasani** [comment]
Reviewed 86 of 86 files at r1.
Review status: 62 of 74 files reviewed at latest revision, 9 unresolved discussions.

---

*[controller/api.go, line 177 at r1](https://reviewable.io:443/reviews/fission/fission/381#-Kxtjcymlk8b-eJ4UNBo:-Kxtjcymlk8b-eJ4UNBp:b-fimi34) ([raw file](https://github.com/fission/fission/blob/71583237346275a7e622db044bcccd7ef31aacd0/controller/api.go#L177)):*
> ```Go
> 	r.HandleFunc("/v2/triggers/messagequeue/{mqTrigger}", api.MessageQueueTriggerApiDelete).Methods("DELETE")
> 
> 	r.HandleFunc("/deleteTpr", api.Tpr2crdApi).Methods("DELETE")
> ```

This should be versioned too.

---

*[controller/api_test.go, line 98 at r1](https://reviewable.io:443/reviews/fission/fission/381#-KxoDXpoB6IM-28bd6lv:-KxoDXpoB6IM-28bd6lw:b-o393ub) ([raw file](https://github.com/fission/fission/blob/71583237346275a7e622db044bcccd7ef31aacd0/controller/api_test.go#L98)):*
> ```Go
> 	m, err := g.client.FunctionCreate(testFunc)
> 	panicIf(err)
> 	defer g.client.FunctionDelete(m)
> ```

This is a good change! But we lost the error check on the function delete return value. How about something like this:

```
defer func() {
    err := g.client.FunctionDelete(m)
    panicIf(err)
}()
```

---

*[controller/api_test.go, line 116 at r1](https://reviewable.io:443/reviews/fission/fission/381#-KxoFO6X5MP9O52swnYJ:-KxoFO6YzOQWyCo08tyo:bgdp87x) ([raw file](https://github.com/fission/fission/blob/71583237346275a7e622db044bcccd7ef31aacd0/controller/api_test.go#L116)):*
> ```Go
> 	funcs, err := g.client.FunctionList()
> 	panicIf(err)
> 	assert(len(funcs) == 2, fmt.Sprintf("created two functions, but find %v", len(funcs)))
> ```

"found"

---

*[controller/tpr2crdApi.go, line 34 at r1](https://reviewable.io:443/reviews/fission/fission/381#-Kxtl3fEXxyado1e4XwM:-Kxtl3fEXxyado1e4XwN:b-2q952f) ([raw file](https://github.com/fission/fission/blob/71583237346275a7e622db044bcccd7ef31aacd0/controller/tpr2crdApi.go#L34)):*
> ```Go
> 	}
> 
> 	tprList, err := kubeClient.ThirdPartyResources().List(metav1.ListOptions{})
> ```

Hey, wait a minute, you can't just delete all TPRs. The user may have other non-fission TPRs on their cluster. We have to specifically only migrate the fission ones.

---

*[crd/crd.go, line 92 at r1](https://reviewable.io:443/reviews/fission/fission/381#-KxtimdbmFzLJDHHxESH:-KxtimdbmFzLJDHHxESI:b-ecfv8h) ([raw file](https://github.com/fission/fission/blob/71583237346275a7e622db044bcccd7ef31aacd0/crd/crd.go#L92)):*
> ```Go
> 				Scope:   apiextensionsv1beta1.NamespaceScoped,
> 				Names: apiextensionsv1beta1.CustomResourceDefinitionNames{
> 					Kind:     "Httptrigger",
> ```

So, when I was making the TPR change, I tried to name these resources with the proper capitalization: HTTPTrigger, KubernetesWatchTrigger, MessageQueueTrigger, etc. etc. But I ran into some errors with the old client-go we were using. It might work with new CRDs and it's basically a big find-replace. Can you try changing the capitalization to CamelCase for all these resources?
```
HTTPTrigger
KubernetesWatchTrigger
TimeTrigger
MessageQueueTrigger
```

---

*[fission/main.go, line 137 at r1](https://reviewable.io:443/reviews/fission/fission/381#-KxtWvLDG0DhjgjAlm9r:-KxtWvLE8At7Cr6ncEPZ:bqurp8n) ([raw file](https://github.com/fission/fission/blob/71583237346275a7e622db044bcccd7ef31aacd0/fission/main.go#L137)):*
> ```Go
> 	migrateFileFlag := cli.StringFlag{Name: "file", Usage: "JSON file containing all CRDs"}
> 	migrateSubCommands := []cli.Command{
> 		{Name: "dump", Usage: "Dump all TPRs into CRDs from a pre-1.8.x Kubernetes cluster", Flags: []cli.Flag{migrateFileFlag}, Action: migrateDumpTPR},
> ```

"Dump all state from a pre-0.4 Fission installation (which used ThirdPartyResources) into a JSON file"

---

*[fission/main.go, line 139 at r1](https://reviewable.io:443/reviews/fission/fission/381#-KxtXcDXGbGrmpeCSDGG:-KxtXcDXGbGrmpeCSDGH:bppcrwr) ([raw file](https://github.com/fission/fission/blob/71583237346275a7e622db044bcccd7ef31aacd0/fission/main.go#L139)):*
> ```Go
> 		{Name: "dump", Usage: "Dump all TPRs into CRDs from a pre-1.8.x Kubernetes cluster", Flags: []cli.Flag{migrateFileFlag}, Action: migrateDumpTPR},
> 		{Name: "delete", Usage: "Delete all TPRs", Flags: []cli.Flag{}, Action: migrateDeleteTPR},
> 		{Name: "restore", Usage: "Restore all CRDs", Flags: []cli.Flag{migrateFileFlag}, Action: migrateRestoreCRD},
> ```

"Restore state dumped from a pre-0.4 Fission cluster. Requires Fission 0.4, which uses Kubernetes CustomResources."

---

*[fission/migrate.go, line 105 at r1](https://reviewable.io:443/reviews/fission/fission/381#-KxtdrmIB_cCnf0gp6dZ:-KxtdrmIB_cCnf0gp6d_:bhq7m7s) ([raw file](https://github.com/fission/fission/blob/71583237346275a7e622db044bcccd7ef31aacd0/fission/migrate.go#L105)):*
> ```Go
> 
> 	if resp.StatusCode == 404 {
> 		msg := fmt.Sprintf("Server %v isn't support deleteTpr method. Use --server to point at a 0.3+ Fission server.", server)
> ```

0.4.0+

---

*[fission/migrate.go, line 130 at r1](https://reviewable.io:443/reviews/fission/fission/381#-KxtiVstBprUEEWSZEJj:-KxtiVstBprUEEWSZEJk:bplazv8) ([raw file](https://github.com/fission/fission/blob/71583237346275a7e622db044bcccd7ef31aacd0/fission/migrate.go#L130)):*
> ```Go
> 	for _, e := range tprResource.Environments {
> 		_, err = client.EnvironmentCreate(&crd.Environment{
> 			Metadata: metav1.ObjectMeta{
> ```

Why can't we use just `e.Metadata` here? There's more in the metadata than Name and Namespace...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fission/fission/381)*

**Comment by life1347** [comment]
*[fission/migrate.go, line 130 at r1](https://reviewable.io:443/reviews/fission/fission/381#-KxtiVstBprUEEWSZEJj:-Ky1m9TJYkFrpfeE7uEa:bbfg2hj) ([raw file](https://github.com/fission/fission/blob/71583237346275a7e622db044bcccd7ef31aacd0/fission/migrate.go#L130)):*
<details><summary><i>Previously, soamvasani (Soam Vasani) wrote…</i></summary><blockquote>

Why can't we use just `e.Metadata` here? There's more in the metadata than Name and Namespace...
</blockquote></details>

After some tests, we need to set Metadata.ResourceVersion as empty string so that we wont get error at creation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fission/fission/381)*

**Comment by life1347** [comment]
Review status: 31 of 76 files reviewed at latest revision, 9 unresolved discussions.

---

*[fission/migrate.go, line 130 at r1](https://reviewable.io:443/reviews/fission/fission/381#-KxtiVstBprUEEWSZEJj:-Ky2VYMifw3sWQ-O_VFe:b-896fix) ([raw file](https://github.com/fission/fission/blob/71583237346275a7e622db044bcccd7ef31aacd0/fission/migrate.go#L130)):*
<details><summary><i>Previously, life1347 (Ta-Ching Chen) wrote…</i></summary><blockquote>

After some tests, we need to set Metadata.ResourceVersion as empty string so that we wont get error at creation.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fission/fission/381)*

**Comment by soamvasani** [comment]
Reviewed 8 of 86 files at r1, 10 of 12 files at r2, 39 of 39 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[Documentation/docs-site/content/upgrade-from-v0.3.md, line 1 at r3](https://reviewable.io:443/reviews/fission/fission/381#-Ky7srvryaF54WoHTX98:-Ky7srvs79836jrzVo0P:bebsn5n) ([raw file](https://github.com/fission/fission/blob/5f954e9525bb1e2c9a71fbe03788432dbc4aa192/Documentation/docs-site/content/upgrade-from-v0.3.md#L1)):*
> ```Markdown
> ---
> ```

Nice work on this doc!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fission/fission/381)*

**Comment by soamvasani** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fission/fission/381#-:-Ky7xglp2967b65qOvTf:bnfp4nl)*

**Pull request merged**
