### PR TITLE
Implement Kafka trigger based on work of @puneetguptanitj

### PR DESCRIPTION
**Pull request by cedbossneo**
This change is [Reviewable](https://reviewable.io/reviews/fission/fission/439)

### CODE REVIEW

**Comment by soamvasani** [comment]
@cedbossneo Thanks for the contribution. Can you instead create a new branch and cherry pick @puneetguptanitj's change into it? That way, commit history is preserved (and we can actually review what changed between the two PRs).

**Comment by cedbossneo** [comment]
Done

**Comment by vishal-biyani** [comment]
Hi @cedbossneo I know it's been a while but I am trying start review on this one. One broad question I had was on the Go library used for Kafka - there is the official one: https://github.com/confluentinc/confluent-kafka-go and there is https://github.com/Shopify/sarama - do you know which would be a better choice?

**Comment by vishal-biyani** [comment]
Commits from this PR have been cherry-picked.
Closing in favor of #831

**Pull request closed without merging**
