### PR TITLE
Java env: Add XML dependency

### PR DESCRIPTION
**Pull request by sahil-lakhwani**
Adds XML support for Spring Rest Controller; for Java environment.
Addresses https://github.com/fission/fission/issues/1505

---
This change is [Reviewable](https://reviewable.io/reviews/fission/fission/1512)

### CODE REVIEW

**Comment by life1347** [comment]
@sahil-lakhwani Hi, I'm wondering do we always need to add extra dependencies for different message formats in the environment dependencies? Or, is it something that the user can add in function dependencies?

**Comment by sahil-lakhwani** [comment]
> @sahil-lakhwani Hi, I'm wondering do we always need to add extra dependencies for different message formats in the environment dependencies? Or, is it something that the user can add in function dependencies?

Hi @life1347, as I understand, a request first lands on the Spring server (env level) , which then calls an overridden method in a (fission) function.
So the problem is at environment level, hence added the dependency there. I am not sure if adding function dependency will help.

**Comment by life1347** [comment]
ok, I see. Would you mind to write an e2e test to verify the change works as expected? You can follow the tests under https://github.com/fission/fission/tree/master/test/tests/test_environments

**Comment by AshishJainRadicle** [comment]
Hi,
I have tried new environment for java xml support but not able.
Tried following steps on windows system.
1- Pull code on locally from "https://github.com/fission/fission.git".
2- Verified "jackson-dataformat-xml" is present in ".\fission\environments\jvm\pom.xml" so i did not added it.
3- Made new docker image locally with "docker build -t ajain1234/javawithxml:latest . "
4- Made new environment with "fission-cli-windows.exe env create --name javawithxml --image ajain1234/javawithxml:latest --version 2"
command.
5-Then made new function with following command
"fission-cli-windows.exe function create --name invoicedetailsashish8960 --deploy hello-world-1.0-SNAPSHOT-jar-with-dependencies.jar --
env javawithxml --entrypoint io.fission.HelloWorld"

And got following response

Package 'invoicedetailsashish8960-c8ddbadf-306a-47c5-9b22-39ec557a10e9' created
function 'invoicedetailsashish8960' created
6- Create route with "fission-cli-windows.exe route create --function invoicedetailsashish8960 --url /invoicedetailsashish8960 --method
POST" command.

 And got following response

 �[33mWarning�[0m: --name will be soon marked as required flag, see 'help' for details
 trigger '5aca39b3-2aea-4f1a-8b2b-8616639b83ab' created
7- Tested by "fission-cli-windows.exe function test --header="Content-Type:text/xml" --body='data' --method='POST' --
name invoicedetailsashish8960" command
And got following response

 **The system cannot find the file specified.**
Please help us.

**Comment by sahil-lakhwani** [comment]
@AshishJainRadicle Would it be possible for you to try this using Fission CLI for Linux/Mac? I am not sure of Windows CLI.

Also, `--body='data' ` is not a valid XML data, so I assume there will be a parsing error.

Is there an elaborated error for this: `The system cannot find the file specified.`?

**Pull request merged**
