### PR TITLE
gevent-based python environment

### PR DESCRIPTION
**Pull request by xiekeyang**
This improves WSGI server's qps under high traffic. For that we introduce `gevent` library.

Like `bjoern`, it runs a WSGI server.

What's more, it throws server into multi-thread under high traffic environment.

Signed-off-by: xiekeyang <keyang.xie@gmail.com>

Below is the comparison of performance between current server and `gevent` server.

With 256 concurrence, 99% requests are finished in 282 ms with `gevent`, quickly than 3815 ms before improvment.

### bjoern
```
$ ab -c 256 -n 8192 http://127.0.0.1:8888/healthz

Benchmarking 127.0.0.1 (be patient)
.......
Finished 8192 requests


Server Software:        
Server Hostname:        127.0.0.1
Server Port:            8888

Document Path:          /healthz
Document Length:        0 bytes

Concurrency Level:      256
Time taken for tests:   4.012 seconds
Complete requests:      8192
Failed requests:        0
Total transferred:      794624 bytes
HTML transferred:       0 bytes
Requests per second:    2041.74 [#/sec] (mean)
Time per request:       125.383 [ms] (mean)
Time per request:       0.490 [ms] (mean, across all concurrent requests)
Transfer rate:          193.41 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0   46 362.0      0    3010
Processing:    10   75  96.9     47    1639
Waiting:        9   75  96.9     47    1639
Total:         13  121 452.1     47    3827

Percentage of the requests served within a certain time (ms)
  50%     47
  66%     86
  75%     97
  80%    100
  90%    108
  95%    124
  98%    157
  99%   3815
 100%   3827 (longest request)
```

### genvet
```
$ ab -c 256 -n 8192 http://127.0.0.1:8888/healthz

Benchmarking 127.0.0.1 (be patient)
.......
Finished 8192 requests


Server Software:        
Server Hostname:        127.0.0.1
Server Port:            8888

Document Path:          /healthz
Document Length:        0 bytes

Concurrency Level:      256
Time taken for tests:   6.388 seconds
Complete requests:      8192
Failed requests:        0
Total transferred:      1097728 bytes
HTML transferred:       0 bytes
Requests per second:    1282.43 [#/sec] (mean)
Time per request:       199.621 [ms] (mean)
Time per request:       0.780 [ms] (mean, across all concurrent requests)
Transfer rate:          167.82 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    2  38.4      0    1004
Processing:    16  194  35.3    189     392
Waiting:       15  193  35.3    189     392
Total:         28  196  52.7    189    1225

Percentage of the requests served within a certain time (ms)
  50%    189
  66%    197
  75%    215
  80%    223
  90%    244
  95%    265
  98%    275
  99%    282
 100%   1225 (longest request)
```

---
This change is [Reviewable](https://reviewable.io/reviews/fission/fission/686)

### CODE REVIEW

**Comment by soamvasani** [comment]
Thanks, @xiekeyang !  I can definitely see the big improvement in the 99%le time.  But it does seem to come at the expense of median (47ms vs 189ms) time, as well as at the expense of throughput (2041 vs 1282 req/s).  Even the 98%le time increases.

**Comment by soamvasani** [comment]
Any thoughts, @life1347 ?  Are there any other advantages to using gevent instead of bjoern?

**Comment by xiekeyang** [comment]
@soamvasani , Thanks, I noticed this. IMO, it should be most considered that the response times of `gevnet` are much more well-distributed than `bjoern`. 

```
  50%    189
  66%    197
  75%    215
  80%    223
  90%    244
  95%    265
  98%    275
  99%    282
 100%   1225 (longest request)
```

**vs**

```
  50%     47
  66%     86
  75%     97
  80%    100
  90%    108
  95%    124
  98%    157
  99%    3815
  100%   3827 (longest request)
```

I think this is because that `bjoern` is a little weak on multi-thread, and it is strong and compact design on WSGI, so it handles first requests so quickly. Meantime `gevent` set up multi-thread cache, and assign requests to different threads.

After long time, `bjoern` reach to its capacity limit and requests have to wait. Meantime, `gevent` has free space to handle them. So it shows `well distributed`.

What's more, my paste above is simple script printing "hello". I tested some higher load script:

```py
import numpy as np
import pandas as pd

def func1(weight, feature, intercept):
    linear_result = sum(weight * feature) + intercept
    prob = 1 / (1 + np.exp(-1 * linear_result))
    b = - (100 / np.log(2))
    a = round(100 + b * np.log(0.1), 0)
    return a - b * prob

def func2(args):
    trans_df = pd.DataFrame({"code": data_code, "standard": data_standard, "woe": data_woe})

    feature_input = []
    none_num = 0
    for feature in features:
        feature_value = args[feature]
        if feature_value is None:
            none_num += 1
        feature_input.append(trans_to_score(trans_df, feature, args[feature]))
    if none_num == len(features):
        return None
    return feature_input
```

The report likes:

### bjoern

The http server is closed because of high load.

```
$ ab -c 256 -n 8192 http://127.0.0.1:8888/
This is ApacheBench, Version 2.3 <$Revision: 1706008 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 819 requests
Completed 1638 requests
Completed 2457 requests
Completed 3276 requests
Completed 4095 requests
Completed 4914 requests
apr_socket_recv: Connection reset by peer (104)
Total of 5637 requests completed
```

### gevent

It can finish without `Failed` request and keep well distribution.

```
$ ab -c 256 -n 8192 http://127.0.0.1:8888/
This is ApacheBench, Version 2.3 <$Revision: 1706008 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 819 requests
Completed 1638 requests
Completed 2457 requests
Completed 3276 requests
Completed 4095 requests
Completed 4914 requests
Completed 5733 requests
Completed 6552 requests
Completed 7371 requests
Completed 8190 requests
Finished 8192 requests


Server Software:        
Server Hostname:        127.0.0.1
Server Port:            8888

Document Path:          /
Document Length:        17 bytes

Concurrency Level:      256
Time taken for tests:   180.330 seconds
Complete requests:      8192
Failed requests:        0
Total transferred:      1245184 bytes
HTML transferred:       139264 bytes
Requests per second:    45.43 [#/sec] (mean)
Time per request:       5635.324 [ms] (mean)
Time per request:       22.013 [ms] (mean, across all concurrent requests)
Transfer rate:          6.74 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   1.4      0      14
Processing:    37 5558 1369.8   5342    8531
Waiting:       37 5557 1369.7   5342    8531
Total:         46 5558 1369.2   5342    8531

Percentage of the requests served within a certain time (ms)
  50%   5342
  66%   6346
  75%   6750
  80%   6899
  90%   7308
  95%   7744
  98%   7966
  99%   8143
 100%   8531 (longest request)
```

After I deploy it on K8S, I observe `gevent` pods and find memory and CPU figure reach high level quickly under high traffic. It is actually better on resource utilization.

**Comment by xiekeyang** [comment]
@soamvasani @life1347 WDYT? thanks.

**Comment by xiekeyang** [comment]
According to well-distributed time, served within shorter time, and be able to support more concurrent requests, I prefer to `gevent`. Please reconsider it. Thanks a lot!

**Comment by life1347** [comment]
@xiekeyang 
I am doing the benchmark for `bjoern` and `gevent`, and will paste result later.

**Comment by life1347** [comment]
Before the result is out, here some thoughts:

1. If the PR tries to improve RPS, then we may need to focus on `Requests per second` since it's not fair to compare two frameworks' 99%le response time that under different RPS.

2. Gevent use multi-thread to serve traffic and increases resourcec utilization, it's ideal if we launch one gevent pod. But for a "function" it's really not a good idea to serve such high load traffic with only one function pod.  In fission's case, newdeploy as function exectortype brings ability of auto-scaling for function. With newdeploy and bjoern, we can have short response time, high rps and also high resource utilization.

**Comment by soamvasani** [comment]
I don't think we have to choose between the two.  I can certainly imagine that there is a use case for a gevent-based environment.  I think the default python environment should remain bjoern, for the median/95%le performance, and for the reasons @life1347 describes above. 

We can have a separate python-gevent directory in the environments, and add it to the build.

**Comment by xiekeyang** [comment]
> We can have a separate python-gevent directory in the environments, and add it to the build.

@soamvasani I think it is a good idea! I would set up another PR to add `gevent` env.

**Pull request closed without merging**
