### PR TITLE
#1132 nodejs environment, increase body size

### PR DESCRIPTION
**Pull request by JannikZed**
This will increase the maximum body-size in the nodejs environment to 1mb, to reflect the NATS maximum message size as written in #1132 
Still some more testing needed.

---
This change is [Reviewable](https://reviewable.io/reviews/fission/fission/1149)

### CODE REVIEW

**Comment by soamvasani** [comment]
LGTM.  (What's the default limit?  I tried googling but couldn't find it easily.)

**Comment by JannikZed** [comment]
Well I understand the documentation of the body-parser like this:

The maximum request body size is 100kb: 

``` 
limit
Controls the maximum request body size. If this is a number, then the value specifies the number of bytes; if it is a string, the value is passed to the bytes library for parsing. Defaults to '100kb'.
``` 
https://www.npmjs.com/package/body-parser#limit

**Comment by JannikZed** [comment]
@soamvasani what do you think? Let's merge? :)

**Comment by soamvasani** [comment]
Thanks for the reminder, @JannikZed.  Yes, I'll merge this.

**Pull request merged**
