### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by ItsJulian**
Completed the mandatory license fields

---
This change is [Reviewable](https://reviewable.io/reviews/fission/fission/1771)

### CODE REVIEW

**Comment by therahulbhati** [comment]
@bhavin192 Can you please take look at this?

**Review by bhavin192 — COMMENTED** [review]
Thank you for showing interest in contributing to Fission. AFAIK these fields are part of the LICENSE, and we should not update them. Even I used to think that one has to update these but that's not the case.

Example: https://github.com/kubernetes/kubernetes/commit/d30db1f9a915aa95402e1190461469a1889d92be

Please checkout other issues too, https://github.com/fission/fission/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

**Comment by ItsJulian** [comment]
Thank you for your feedback. 

The apache website says the following about the LICENSE template variables: https://www.apache.org/licenses/LICENSE-2.0

> To apply the Apache License to specific files in your work, attach the following boilerplate declaration, with the fields enclosed by brackets "[]" replaced with your own identifying information. (Don't include the brackets!)

**Comment by bhavin192** [comment]
Right, that is for a specific file and not the LICENSE file itself. For example, if I'm adding a new file called function.go, I will add the given boilerplate and replace the placeholders.

**Comment by ItsJulian** [comment]
Okay I get it! Thanks for clarifying!

**Comment by ItsJulian** [comment]
i am closing this PR because it is the same as https://github.com/fission/fission/pull/1771

**Pull request closed without merging**
