### PR TITLE
include path parameters in params hash for ruby environment

### PR DESCRIPTION
**Pull request by sbfaulkner**
this PR adds a helper method in the ruby context/request to make using path parameters easier

e.g.
given a route /path/:id
and a request for /path/123
a header would be present with the form `X-Fission-Params-Id: 123`
and with this update `request.params` would return the hash `{'id' => '123'}`

### CODE REVIEW

**Comment by soamvasani** [comment]
Thanks @sbfaulkner ! Mind updating the README with this info?

**Comment by sbfaulkner** [comment]
@soamvasani updated README(s) and improved structure of ruby env

**Comment by sbfaulkner** [comment]
(logger addition will follow in another PR yet to be written)

**Comment by soamvasani** [comment]
Awesome update! 😄 Merging now.

**Pull request merged**
