### PR TITLE
Allow unique HTTP route & method (#102)

### PR DESCRIPTION
**Pull request by kphatak**
Testing Done:
$ fission route create --method POST --url /test-routes --function test-r
trigger '6b90a150-9a9f-4737-981f-3faabfef3580' created

$ fission route create --method GET --url /test-routes --function test-r
trigger 'bd48e8d6-519f-4ebd-9b86-aa985cd63c7b' created

$ fission route create --method POST --url /test-routes --function test-r
ERRO[0000] Failed to create http trigger                 err="(Error 0) HTTP error 409" name=6d0a8286-99da-4315-9aaf-775308d5d994
Failed to create HTTP trigger: (Error 0) HTTP error 409

### CODE REVIEW

**Comment by soamvasani** [comment]
Thanks @kaustubhvp !  This look good and I can merge it; but since you're here, would you also like to fix the HTTPTriggerApiUpdate function to look for a duplicate route?

**Comment by kaustubhvp** [comment]
@soamvasani sure. I will fix it and commit to this PR.

**Comment by soamvasani** [comment]
@kaustubhvp and i spoke offline, he'll rebase on top of #116 after it's merged.  Thanks!

**Comment by soamvasani** [comment]
@kphatak #116 is merged, would you mind rebasing?  Thanks!

**Pull request merged**
