### PR TITLE
Convert go-env Dockerfile into a multi-stage build

### LINKED ISSUE #624: Runtime environment for Go should be alpine or scratch
Hi, your current runtime images for go are very large - is there any chance that you could migrate the go runtimes to alpine or scratch so that there is less deployment overhead?

Thanks!

### PR DESCRIPTION
**Pull request by jgall**
Converting to a multi-stage build reduces the size of the final image from ~750MB to ~15MB.

Fixes #624

---
This change is [Reviewable](https://reviewable.io/reviews/fission/fission/683)

### CODE REVIEW

**Comment by jgall** [comment]
Someone might want to run some more regression tests than I was able to run locally before this is merged just to check that some larger existing fission workflows don't break (although I'm not sure why they would).

**Comment by vishal-biyani** [comment]
Thanks @jgall for the PR. Do you mind rebasing from master and updating this PR please?

**Comment by jgall** [comment]
Rebased

**Comment by soamvasani** [comment]
Whoa, awesome, thanks!  Looks good theoretically, I'll test this at bit more manually and then merge it.

**Comment by life1347** [comment]
LGTM. I'm able to build and launch container locally.

**Pull request merged**
