### PR TITLE
Add support for Kafka record headers

### PR DESCRIPTION
**Pull request by bhavin192**
- Add support for Kafka record headers

  - This makes sure that the headers received from a function are
  converted to Kafka record headers
  - Also extracts the headers from a Kafka record and sends them to
  function
  - ref: https://issues.apache.org/jira/browse/KAFKA-4208

- Make Kafka version configurable

  - Adds version field to Kafka struct
  - Adds `MESSAGE_QUEUE_KAFKA_VERSION` environment variable
  - Drop headers from Kafka record if specified Kafka version is `< 0.11.0.0`

- Update helm chart fission-all for Kafka record headers

  - Adds new field `kafka.version`
  - Sets the `MESSAGE_QUEUE_KAFKA_VERSION` environments variable to `kafka.version`

---
This change is [Reviewable](https://reviewable.io/reviews/fission/fission/1025)

### CODE REVIEW

**Comment by bhavin192** [comment]
Not sure why the build is failing. It passes on my fork which has same `.travis.yaml`  (only allowed branches and `go_import_path: github.com/fission/fission` are changed)
https://travis-ci.org/bhavin192/fission/jobs/469912067/config

**Comment by life1347** [comment]
LGTM, just two minor comments.

**Comment by bhavin192** [comment]
Hey @life1347 I have made changes according to your suggestions.
> BTW, the PR description for changes is awesome.

Hehe, thanks :)

**Comment by life1347** [comment]
LGTM. please rebase master and we can merge it when ci passed

**Comment by bhavin192** [comment]
Here is the output of integration test of kafka 

```console
Creating node-kafka environment
environment 'node-kafka' created
Creating go-kafka environment
environment 'go-kafka' created
Creating package for Kafka producer
...
Output of glide install
...
pkgName=kafka-zip-3lwb
~/work/go/src/github.com/fission/fission/test/tests/mqtrigger/kafka
Waiting for builder manager to finish the build
Waiting for build to finish
Waiting for build to finish
Waiting for build to finish
Waiting for build to finish
succeeded
Package kafka-zip-3lwb created
Creating function consumer-func
function 'consumer-func' created
Creating function consumer-func2
function 'consumer-func2' created
Creating function producer-func
function 'producer-func' created
Creating trigger kafkatest
trigger 'kafkatest' created
Creating trigger kafkatest2
trigger 'kafkatest2' created
Successfully sent to testtopicTesting pool manager function
Checking for valid response
level=info msg="Calling message handler with value {"name": "testvalue"}" time="2019-01-11T10:07:18Z" level=info msg="Making HTTP request to http://router.fission/fission-function/consumer-func"
Testing the headers values in consumer-func
Checking for valid function log
> fission-nodejs-runtime@0.1.0 start /usr/src/app > node server.js user code loaded in 0sec 0.354236ms ::1 - - [11/Jan/2019:10:03:23 +0000] "POST /specialize HTTP/1.1" 202 - "-" "Go-http-client/1.1" { name: 'testvalue' } z-custom-name: Kafka-Header-test x-fission-function-name: consumer-func ::ffff:10.36.0.6 - - [11/Jan/2019:10:03:23 +0000] "POST / HTTP/1.1" 200 20 "-" "Go-http-client/1.1" > fission-nodejs-runtime@0.1.0 start /usr/src/app > node server.js user code loaded in 0sec 3.618165ms ::1 - - [11/Jan/2019:10:07:18 +0000] "POST /specialize HTTP/1.1" 202 - "-" "Go-http-client/1.1" { name: 'testvalue' } z-custom-name: Kafka-Header-test x-fission-function-name: consumer-func ::ffff:10.36.0.6 - - [11/Jan/2019:10:07:18 +0000] "POST / HTTP/1.1" 200 20 "-" "Go-http-client/1.1"
Testing the header value in consumer-func2
Checking for valid function log
> fission-nodejs-runtime@0.1.0 start /usr/src/app > node server.js user code loaded in 0sec 0.222792ms ::1 - - [11/Jan/2019:10:03:23 +0000] "POST /specialize HTTP/1.1" 202 - "-" "Go-http-client/1.1" { name: 'testvalue' } z-custom-name: Kafka-Header-test x-fission-function-name: consumer-func2 ::ffff:10.36.0.6 - - [11/Jan/2019:10:03:23 +0000] "POST / HTTP/1.1" 200 20 "-" "Go-http-client/1.1" > fission-nodejs-runtime@0.1.0 start /usr/src/app > node server.js user code loaded in 0sec 0.407005ms ::1 - - [11/Jan/2019:10:07:19 +0000] "POST /specialize HTTP/1.1" 202 - "-" "Go-http-client/1.1" { name: 'testvalue' } z-custom-name: Kafka-Header-test x-fission-function-name: consumer-func2 ::ffff:10.36.0.6 - - [11/Jan/2019:10:07:19 +0000] "POST / HTTP/1.1" 200 20 "-" "Go-http-client/1.1"
Checking for valid function log
> fission-nodejs-runtime@0.1.0 start /usr/src/app > node server.js user code loaded in 0sec 0.222792ms ::1 - - [11/Jan/2019:10:03:23 +0000] "POST /specialize HTTP/1.1" 202 - "-" "Go-http-client/1.1" { name: 'testvalue' } z-custom-name: Kafka-Header-test x-fission-function-name: consumer-func2 ::ffff:10.36.0.6 - - [11/Jan/2019:10:03:23 +0000] "POST / HTTP/1.1" 200 20 "-" "Go-http-client/1.1" > fission-nodejs-runtime@0.1.0 start /usr/src/app > node server.js user code loaded in 0sec 0.407005ms ::1 - - [11/Jan/2019:10:07:19 +0000] "POST /specialize HTTP/1.1" 202 - "-" "Go-http-client/1.1" { name: 'testvalue' } z-custom-name: Kafka-Header-test x-fission-function-name: consumer-func2 ::ffff:10.36.0.6 - - [11/Jan/2019:10:07:19 +0000] "POST / HTTP/1.1" 200 20 "-" "Go-http-client/1.1"
Cleaning up...
environment 'go-kafka' deleted
environment 'node-kafka' deleted
function 'producer-func' deleted
function 'consumer-func' deleted
function 'consumer-func2' deleted
trigger 'kafkatest' deleted
trigger 'kafkatest2' deleted
```

**Comment by vishal-biyani** [comment]
@life1347 The build fails with same PR's code here: https://github.com/fission/fission/pull/1052 and also the test was enhanced to test changes in this PR and tested locally (As it needs Kafka cluster setup). Looks good?

**Comment by life1347** [comment]
yes, looks great. We can merge it 🎉

**Comment by vishal-biyani** [comment]
Build in https://github.com/fission/fission/pull/1052 is green for the same change. This change has been tested in a local setup with Kafka cluster and working as expected with test. Merging.

Thanks a lot, @bhavin192 for your contribution!

**Pull request merged**
