### PR TITLE
Function update after change in env

### PR DESCRIPTION
**Pull request by vishal-biyani**
This fixes: https://github.com/fission/fission/issues/929

---
This change is [Reviewable](https://reviewable.io/reviews/fission/fission/1116)

### CODE REVIEW

**Comment by vishal-biyani** [comment]
Summary of change:

1) Added a new controller to newdeploy. Every time an env updates - it will check for all related functions and simply update the resource version of fn with the latest resource version of env.

The actual update of newdeploy deployment is done by an existing controller for functions.

2) From a CLI - when you create a function - the resource version of the environment is retrieved and updated to function. I think is going to break scenarios where someone creates a function first and env later (And I think this anyway does not work for newdeploy as of now)

3) For Specs - similar update to function resourceversion

I think this change is going to break the existing deployments and we will have to update existing functions to get the env version of environments as a one-time upgrade activity!

**Comment by life1347** [comment]
For some environment like Go it's dangerous to do automatically upgrade since the compiled plugin may not fit for the new image. How about exposing a new flag in CLI and let users choose whether updating or not? (By default, we don't do upgrade automatically.)

**Comment by vishal-biyani** [comment]
Hi @life1347 I am not sure I understand the flag - will flag differ the update of the image for existing pods or what exactly it will do?

Secondly, as of now the poolmanager immediately re-creates the pool after the image is updated for an environment so I think keeping the behavior consistent is probably a better idea.

I am worried about cross resource updates and the right design for that. Currently, we have a tight dependency between env, package, and function in terms of creation - which is not desirable. I am still exploring Kubernetes docs to see if this is a solved pattern and we should use that instead of current solution in the code of this PR.

**Comment by life1347** [comment]
Yeah, you're right for the consistent behavior for executors. Or how about we can add some description text to CLI help to explain potential problem if update an environment?

```
NAME:
   fission environment update - Update environment

USAGE:
   fission environment update [command options] [arguments...]

DESCRIPTION:
   some text here
```

You can add a description with like the following 
```
{Name: "update", Usage: "Update environment", Description: "some text here" .....
```

**Comment by vishal-biyani** [comment]
@ajbouh & @soamvasani This was PR we were discussing for comments in the call.

**Comment by soamvasani** [comment]
I wonder if you can put this same controller into `newdeploymgr`, and call `deploy.updateFunction` on all functions for that environment whenever an environment changes?

For finding the functions of an env you could either iterate over them all in the store or keep a env->fn map and update it from the function controller that's already there.

**Comment by ajbouh** [comment]
I didn't see anything in this change that invalidates the function cache in router. What happens to incoming requests when old function environments are being "updated"?

**Comment by soamvasani** [comment]
> I didn't see anything in this change that invalidates the function cache in router. What happens to incoming requests when old function environments are being "updated"?

I think the idea is that by updating the function CRD itself, all of the logic around function updates gets triggered.  The router cache (functionServiceMap) uses the resource version in the cache key, so updates get handled properly, in this diff.

But, now I realize that my proposal to leave the CRD unchanged and just redeploy the pod(s) is not so simple, because the router cache would also need changing.

**Comment by ajbouh** [comment]
There's also a race condition, isn't there? Where incoming request gets routed to a function that's shut(ting) down?

**Comment by soamvasani** [comment]
> There's also a race condition, isn't there? Where incoming request gets routed to a function that's shut(ting) down?

The functionServiceMap cache has an expiry of 1 minute, and the pods are killed after 6 minutes.  So as long as requests are shorter than 5 minutes, we're ok.

**Comment by vishal-biyani** [comment]
@soamvasani and @ajbouh - changed PR to not break the API. 

As far `The router cache (functionServiceMap) ` - the router uses Service URL for newdeploy executor so cache does not need an update.

Lastly - We would have to add a rolling upgrade and maxUnavailable for newdeploy deployment - with some defaults , will do that in a separate PR

**Pull request merged**
