### PR TITLE
Executor abstraction

### PR DESCRIPTION
**Pull request by vishal-biyani**
This change introduces executor between router and pool manager as part of #193. ATM the default backend is pool manager, more will be added in future.

---
This change is [Reviewable](https://reviewable.io/reviews/fission/fission/384)

### CODE REVIEW

**Comment by soamvasani** [comment]
Reviewed 22 of 27 files at r1, 8 of 8 files at r3.
Review status: 22 of 23 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[charts/fission-all/templates/deployment.yaml, line 296 at r3](https://reviewable.io:443/reviews/fission/fission/384#-KzAuyhXswam7QOcGudb:-KzAuyhXswam7QOcGudc:b-cugoed) ([raw file](https://github.com/fission/fission/blob/b540ad2b0b54e4550e566c50c01687134e3000b2/charts/fission-all/templates/deployment.yaml#L296)):*
> ```YAML
> kind: Deployment
> metadata:
>   name: executor
> ```

This file now seems to have two `executor` deployments (and two exectuor services as well).  It should be failing the build... 

---

*[charts/fission-all/templates/deployment.yaml, line 311 at r3](https://reviewable.io:443/reviews/fission/fission/384#-KzAuTq9qd9JU4on8hVj:-KzAuTqAbm-ITaLOe-M4:b-2qiujx) ([raw file](https://github.com/fission/fission/blob/b540ad2b0b54e4550e566c50c01687134e3000b2/charts/fission-all/templates/deployment.yaml#L311)):*
> ```YAML
>         imagePullPolicy: {{ .Values.pullPolicy }}
>         command: ["/fission-bundle"]
>         args: ["--executorPort", "8890", "--poolmgrUrl", "http://poolmgr.{{ .Release.Namespace }}"]
> ```

Why not change `--poolmgrUrl` to `--executorUrl`?

---

*[executor/executor.go, line 42 at r3](https://reviewable.io:443/reviews/fission/fission/384#-KzAwhauuegkOSn5nbjq:-KzAwhauuegkOSn5nbjr:bz534nl) ([raw file](https://github.com/fission/fission/blob/b540ad2b0b54e4550e566c50c01687134e3000b2/executor/executor.go#L42)):*
> ```Go
> 
> 		requestChan chan *createFuncServiceRequest
> 		fsCreateWg  map[string]*sync.WaitGroup // xxx no channels here, rename this
> ```

this comment can be removed

---

*[executor/executor.go, line 50 at r3](https://reviewable.io:443/reviews/fission/fission/384#-KzAwtglxhqT_ocuUcDf:-KzAwtglxhqT_ocuUcDg:b-uoujmx) ([raw file](https://github.com/fission/fission/blob/b540ad2b0b54e4550e566c50c01687134e3000b2/executor/executor.go#L50)):*
> ```Go
> 
> 	createFuncServiceResponse struct {
> 		address string
> ```

maybe return the object reference as well?

---

*[executor/executor.go, line 125 at r3](https://reviewable.io:443/reviews/fission/fission/384#-KzAzlqv4b0Mi8Xtogcd:-KzAzlqwwOsnvDoIamVw:b-doxht4) ([raw file](https://github.com/fission/fission/blob/b540ad2b0b54e4550e566c50c01687134e3000b2/executor/executor.go#L125)):*
> ```Go
> 
> 	// from Func -> get Env
> 	log.Printf("[%v] getting environment for function", m.Name)
> ```

can you remove this log? there's already a log inside `getFunctionEnv` for the uncached case

---

*[executor/executor.go, line 131 at r3](https://reviewable.io:443/reviews/fission/fission/384#-KzAyjLDuXtgwk0xfCNB:-KzAyjLDuXtgwk0xfCNC:bb7u2jq) ([raw file](https://github.com/fission/fission/blob/b540ad2b0b54e4550e566c50c01687134e3000b2/executor/executor.go#L131)):*
> ```Go
> 	}
> 	// Appropriate backend handles the service creation
> 	backend := os.Getenv("BACKEND")
> ```

can you name this something more descriptive like DEFAULT_EXECUTOR_BACKEND?

---

*[executor/poolmgr_test.go, line 1 at r3](https://reviewable.io:443/reviews/fission/fission/384#-KzB0NYyr-Azeo0IW0v0:-KzB0NYziXDW71aXDAmL:b-h8vyn1) ([raw file](https://github.com/fission/fission/blob/b540ad2b0b54e4550e566c50c01687134e3000b2/executor/poolmgr_test.go#L1)):*
> ```Go
> //
> ```

Suggest just deleting this file.  (Unless you found it useful.) At the moment is dead code.

---

*[executor/fcache/functionServiceCache.go~HEAD, line 1 at r3](https://reviewable.io:443/reviews/fission/fission/384#-KzB0dRsAYL74_62ZmDR:-KzB0dRsAYL74_62ZmDS:b2g5rxp) ([raw file](https://github.com/fission/fission/blob/b540ad2b0b54e4550e566c50c01687134e3000b2/executor/fcache/functionServiceCache.go~HEAD#L1)):*
> ```
> /*
> ```

merge problem?

---

*[executor/fcache/functionServiceCache_test.go~HEAD, line 1 at r3](https://reviewable.io:443/reviews/fission/fission/384#-KzB-DSPjYtnbJWoam1f:-KzB-DSPjYtnbJWoam1g:bv7orrj) ([raw file](https://github.com/fission/fission/blob/b540ad2b0b54e4550e566c50c01687134e3000b2/executor/fcache/functionServiceCache_test.go~HEAD#L1)):*
> ```
> package fcache
> ```

something's messed up in this file, bad filename and merge conflicts in here

---

*[executor/poolmgr/gp.go, line 47 at r3](https://reviewable.io:443/reviews/fission/fission/384#-KzB-nnsb6m6KfwbAtF7:-KzB-nnsb6m6KfwbAtF8:ba2vowr) ([raw file](https://github.com/fission/fission/blob/b540ad2b0b54e4550e566c50c01687134e3000b2/executor/poolmgr/gp.go#L47)):*
> ```Go
> 	"github.com/fission/fission/environments/fetcher"
> 	fetcherClient "github.com/fission/fission/environments/fetcher/client"
> 	"github.com/fission/fission/executor/fcache"
> ```

can we call it `fscache`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fission/fission/384)*

**Comment by soamvasani** [comment]
Review status: 22 of 23 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[executor/poolmgr/gp.go, line 580 at r3](https://reviewable.io:443/reviews/fission/fission/384#-KzB2L8ufaxGSgwDitZN:-KzB2L8ufaxGSgwDitZO:bva52ip) ([raw file](https://github.com/fission/fission/blob/b540ad2b0b54e4550e566c50c01687134e3000b2/executor/poolmgr/gp.go#L580)):*
> ```Go
> 	}
> 
> 	err, existingFsvc := gp.fsCache.Add(*fsvc)
> ```

I think we can move this to the executor layer.

---

*[executor/poolmgr/gp.go, line 583 at r3](https://reviewable.io:443/reviews/fission/fission/384#-KzB1z3o2dGV0KXG-Tqo:-KzB1z3o2dGV0KXG-Tqp:b-xk0k24) ([raw file](https://github.com/fission/fission/blob/b540ad2b0b54e4550e566c50c01687134e3000b2/executor/poolmgr/gp.go#L583)):*
> ```Go
> 	if err != nil {
> 		if fe, ok := err.(fission.Error); ok {
> 			if fe.Code == fission.ErrorNameExists {
> ```

i think this is dead code?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fission/fission/384)*

**Comment by vishal-biyani** [comment]
Addressed 

---

Review status: 13 of 20 files reviewed at latest revision, 12 unresolved discussions.

---

*[charts/fission-all/templates/deployment.yaml, line 296 at r3](https://reviewable.io:443/reviews/fission/fission/384#-KzAuyhXswam7QOcGudb:-KzBcDhnbrat7prGWZM6:b-896fix) ([raw file](https://github.com/fission/fission/blob/b540ad2b0b54e4550e566c50c01687134e3000b2/charts/fission-all/templates/deployment.yaml#L296)):*
<details><summary><i>Previously, soamvasani (Soam Vasani) wrote…</i></summary><blockquote>

This file now seems to have two `executor` deployments (and two exectuor services as well).  It should be failing the build... 
</blockquote></details>

Done.

---

*[charts/fission-all/templates/deployment.yaml, line 311 at r3](https://reviewable.io:443/reviews/fission/fission/384#-KzAuTq9qd9JU4on8hVj:-KzBDdOmfuMualalZbma:bkcoecn) ([raw file](https://github.com/fission/fission/blob/b540ad2b0b54e4550e566c50c01687134e3000b2/charts/fission-all/templates/deployment.yaml#L311)):*
<details><summary><i>Previously, soamvasani (Soam Vasani) wrote…</i></summary><blockquote>

Why not change `--poolmgrUrl` to `--executorUrl`?
</blockquote></details>

This is from the additional redundant deployment, this is done away in latest one.

---

*[executor/executor.go, line 42 at r3](https://reviewable.io:443/reviews/fission/fission/384#-KzAwhauuegkOSn5nbjq:-KzBcC4D0u5caH5SxYv7:b-896fix) ([raw file](https://github.com/fission/fission/blob/b540ad2b0b54e4550e566c50c01687134e3000b2/executor/executor.go#L42)):*
<details><summary><i>Previously, soamvasani (Soam Vasani) wrote…</i></summary><blockquote>

this comment can be removed
</blockquote></details>

Done.

---

*[executor/executor.go, line 50 at r3](https://reviewable.io:443/reviews/fission/fission/384#-KzAwtglxhqT_ocuUcDf:-KzBcACtKgXMIubASlFu:b-896fix) ([raw file](https://github.com/fission/fission/blob/b540ad2b0b54e4550e566c50c01687134e3000b2/executor/executor.go#L50)):*
<details><summary><i>Previously, soamvasani (Soam Vasani) wrote…</i></summary><blockquote>

maybe return the object reference as well?
</blockquote></details>

Done.

---

*[executor/executor.go, line 125 at r3](https://reviewable.io:443/reviews/fission/fission/384#-KzAzlqv4b0Mi8Xtogcd:-KzBc7c76UVGYO1Liti6:b-896fix) ([raw file](https://github.com/fission/fission/blob/b540ad2b0b54e4550e566c50c01687134e3000b2/executor/executor.go#L125)):*
<details><summary><i>Previously, soamvasani (Soam Vasani) wrote…</i></summary><blockquote>

can you remove this log? there's already a log inside `getFunctionEnv` for the uncached case
</blockquote></details>

Done.

---

*[executor/executor.go, line 131 at r3](https://reviewable.io:443/reviews/fission/fission/384#-KzAyjLDuXtgwk0xfCNB:-KzBFK0-n-KzX7ce7fBY:bb6un1j) ([raw file](https://github.com/fission/fission/blob/b540ad2b0b54e4550e566c50c01687134e3000b2/executor/executor.go#L131)):*
<details><summary><i>Previously, soamvasani (Soam Vasani) wrote…</i></summary><blockquote>

can you name this something more descriptive like DEFAULT_EXECUTOR_BACKEND?
</blockquote></details>

Done

---

*[executor/poolmgr/gp.go, line 47 at r3](https://reviewable.io:443/reviews/fission/fission/384#-KzB-nnsb6m6KfwbAtF7:-KzBc2_TkBvUgTu5RQ-M:b-896fix) ([raw file](https://github.com/fission/fission/blob/b540ad2b0b54e4550e566c50c01687134e3000b2/executor/poolmgr/gp.go#L47)):*
<details><summary><i>Previously, soamvasani (Soam Vasani) wrote…</i></summary><blockquote>

can we call it `fscache`
</blockquote></details>

Done.

---

*[executor/poolmgr/gp.go, line 580 at r3](https://reviewable.io:443/reviews/fission/fission/384#-KzB2L8ufaxGSgwDitZN:-KzBYZ65YiBJCXEOu1Ei:b1uabyi) ([raw file](https://github.com/fission/fission/blob/b540ad2b0b54e4550e566c50c01687134e3000b2/executor/poolmgr/gp.go#L580)):*
<details><summary><i>Previously, soamvasani (Soam Vasani) wrote…</i></summary><blockquote>

I think we can move this to the executor layer.
</blockquote></details>

@soam I don't think we can move this as of today to executor layer - because this is cache used at generic pool level to add, for reaping of idle pods etc. So it might be a good idea to look at this in a separate change rather than just moving this out for now.

---

*[executor/poolmgr/gp.go, line 583 at r3](https://reviewable.io:443/reviews/fission/fission/384#-KzB1z3o2dGV0KXG-Tqo:-KzBc-GVLzS0GX2mr3a0:b-896fix) ([raw file](https://github.com/fission/fission/blob/b540ad2b0b54e4550e566c50c01687134e3000b2/executor/poolmgr/gp.go#L583)):*
<details><summary><i>Previously, soamvasani (Soam Vasani) wrote…</i></summary><blockquote>

i think this is dead code?
</blockquote></details>

Done.

---

*[executor/poolmgr_test.go, line 1 at r3](https://reviewable.io:443/reviews/fission/fission/384#-KzB0NYyr-Azeo0IW0v0:-KzBc4vzq8MGx5QbvgY8:b-896fix) ([raw file](https://github.com/fission/fission/blob/b540ad2b0b54e4550e566c50c01687134e3000b2/executor/poolmgr_test.go#L1)):*
<details><summary><i>Previously, soamvasani (Soam Vasani) wrote…</i></summary><blockquote>

Suggest just deleting this file.  (Unless you found it useful.) At the moment is dead code.
</blockquote></details>

Done.

---

*[executor/fcache/functionServiceCache.go~HEAD, line 1 at r3](https://reviewable.io:443/reviews/fission/fission/384#-KzB0dRsAYL74_62ZmDR:-KzBc4Ek7bVLLJApTgZM:b-896fix) ([raw file](https://github.com/fission/fission/blob/b540ad2b0b54e4550e566c50c01687134e3000b2/executor/fcache/functionServiceCache.go~HEAD#L1)):*
<details><summary><i>Previously, soamvasani (Soam Vasani) wrote…</i></summary><blockquote>

merge problem?
</blockquote></details>

Done.

---

*[executor/fcache/functionServiceCache_test.go~HEAD, line 1 at r3](https://reviewable.io:443/reviews/fission/fission/384#-KzB-DSPjYtnbJWoam1f:-KzBc3hXaHAU-k4JOcac:b-896fix) ([raw file](https://github.com/fission/fission/blob/b540ad2b0b54e4550e566c50c01687134e3000b2/executor/fcache/functionServiceCache_test.go~HEAD#L1)):*
<details><summary><i>Previously, soamvasani (Soam Vasani) wrote…</i></summary><blockquote>

something's messed up in this file, bad filename and merge conflicts in here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fission/fission/384#-:-KzBm0fx2rbn5R1cvSSj:bvljs2a)*

**Comment by soamvasani** [comment]
LGTM

---

Reviewed 4 of 29 files at r1, 12 of 12 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[executor/poolmgr/gp.go, line 580 at r3](https://reviewable.io:443/reviews/fission/fission/384#-KzB2L8ufaxGSgwDitZN:-KzQYxyABI7gXqizWA5R:b-u3qkpc) ([raw file](https://github.com/fission/fission/blob/b540ad2b0b54e4550e566c50c01687134e3000b2/executor/poolmgr/gp.go#L580)):*
<details><summary><i>Previously, vishal-biyani (Vishal) wrote…</i></summary><blockquote>

@soam I don't think we can move this as of today to executor layer - because this is cache used at generic pool level to add, for reaping of idle pods etc. So it might be a good idea to look at this in a separate change rather than just moving this out for now.
</blockquote></details>

Sounds ok to me

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fission/fission/384#-:-KzQZDJBLVASZmPdbW4w:bb6ywmx)*

**Pull request merged**
