### PR TITLE
Fix environment version validation

### PR DESCRIPTION
**Pull request by davidsmf**
The checking did nothing.... are there tests I can add to?

---
This change is [Reviewable](https://reviewable.io/reviews/fission/fission/1253)

### CODE REVIEW

**Comment by life1347** [comment]
If you don't mind to write tests for validation you can add `validation_test.go` under `pkg/apis/fission.io/v1`. And thanks for the PR!

**Comment by davidsmf** [comment]
I didn't manage to get the tests running locally - the build process under windows is really bad, and something seems to be broken in Go in my linux VM.

**Comment by life1347** [comment]
What go version you used to build the docker image?

You can build the cli and image like following.

```
# cli
$ cd $GOPATH/src/github.com/fission/fission/cmd/fission-cli
$ go build -o fission .

# bundle image
$ cd $GOPATH/src/github.com/fission/fission
$ docker build -t fission-bundle:1 -f cmd/fission-bundle/Dockerfile.fission-bundle .
```

**Comment by life1347** [comment]
@davidsmf Thanks for the PR! Let's merge this first. We can add tests later.

**Pull request merged**
