### PR TITLE
Use latest for stable release of minikube

### PR DESCRIPTION
**Pull request by r2d4**
The latest stable release for minikube is published at
storage.googleapis.com/minikube/releases/latest

### CODE REVIEW

**Comment by soamvasani** [comment]
Yeah... I admit I'm a little nervous about automatically pulling in the latest version, even though minikube is pretty stable.  @r2d4 would you mind changing this to '0.16.0' instead of latest?

**Comment by r2d4** [comment]
Makes sense.  Changed it to the latest version.

**Comment by r2d4** [comment]
It's worth it to note that minikube is actually compatible with a bunch of versions of kubernetes.  If you do ever run into issues with compatibility, you can always 'sticky' a version of kubernetes with 

`minikube config set kubernetes-version v1.5.2`

**Comment by soamvasani** [comment]
Thanks! And good to know about `minikube config set`.

**Pull request merged**
