### PR TITLE
Update function_test.go

### PR DESCRIPTION
**Pull request by tacoelho**
Print HTTP request and response (meta)data in verbose mode #880

---
This change is [Reviewable](https://reviewable.io/reviews/fission/fission/1844)

### CODE REVIEW

**Comment by therahulbhati** [comment]
@tacoelho Thanks for the PR, can please fix this https://travis-ci.org/github/fission/fission/builds/737518305#L589 so that build turns green.

**Comment by vishal-biyani** [comment]
Hi @tacoelho I am sorry but formatting issues can you please run gofmt. Also, I am not sure I understand the code fully as it does not look like getting called from anywhere. Can you please explain what you are trying to do?

**Comment by tacoelho** [comment]
> Hi @tacoelho I am sorry but formatting issues can you please run gofmt. Also, I am not sure I understand the code fully as it does not look like getting called from anywhere. Can you please explain what you are trying to do?

I can't get it to run. Iḿ trying to get the url metadata in verbose mode as requested.

**Comment by vishal-biyani** [comment]
Hi @tacoelho I am closing this for now, please reopen once you have it working.

**Pull request closed without merging**
