### PR TITLE
Bump Travis versions

### PR DESCRIPTION
**Pull request by HaraldNordgren**
This change is [Reviewable](https://reviewable.io/reviews/fission/fission/945)

### CODE REVIEW

**Comment by life1347** [comment]
Hi @HaraldNordgren thanks for the PR.
But would you mind to separate the code change and .travis.yml into two PRs. Thanks

**Comment by HaraldNordgren** [comment]
@life1347 Unfortunately I had to update a bunch of files to make the tests pass. So not really sure how one change makes sense without the other one.

**Comment by life1347** [comment]
Hi @HaraldNordgren , sorry maybe I am not clear and make you feel confused.

I mean the code changes are very helpful for codebase also it didn't rely on travis changes. So if you can separate code changes to another PR, then we can merge it first 

For the travis part, in fact we already do helm installation in ack/travis-kube-setup.sh

https://github.com/fission/fission/blob/a714983c284fd295d3fdf4d2937c6aec2ee5b99d/hack/travis-kube-setup.sh#L34

So we need to take some time to figure out what makes your travis changes failed and maybe delay the merge time.

**Comment by life1347** [comment]
https://github.com/fission/fission/pull/999 merged, close this one. Thanks for @HaraldNordgren  contribution!

**Pull request closed without merging**
