### PR TITLE
Make mergePodSpec pick up enableServiceLinks

### PR DESCRIPTION
**Pull request by darkworon**
Fixes https://github.com/fission/fission/issues/1599

---
This change is [Reviewable](https://reviewable.io/reviews/fission/fission/1601)

### CODE REVIEW

**Comment by vishal-biyani** [comment]
Thank you so much for the quick one @darkworon I will test, run integration test and merge this tomorrow my morning!

**Comment by darkworon** [comment]
@vishal-biyani thank you!

**Comment by vishal-biyani** [comment]
Thanks - I just tested this and it works. 
Before this feature, you can see that many env variables are seen in function pod:

```
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=poolmgr-python-default-16369431-6c95f8f9b6-4tz25
TERM=xterm
NEWDEPLOY_DATA_DEFAULT_8A6E_F31F3A19743F_PORT_80_TCP_ADDR=10.88.0.4
NEWDEPLOY_KC_DEFAULT_83E3_706C9BF6C12E_SERVICE_PORT_HTTP_ENV=80
NEWDEPLOY_FUELAVG_DEFAULT_A34F_D1AF3C3652B2_SERVICE_HOST=10.88.12.131
NEWDEPLOY_FUELAVG_DEFAULT_A34F_D1AF3C3652B2_PORT_80_TCP_ADDR=10.88.12.131
NEWDEPLOY_FUELAVG_DEFAULT_A34F_D1AF3C3652B2_SERVICE_PORT=80
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_PORT_443_TCP_ADDR=10.88.0.1
NEWDEPLOY_KP_DEFAULT_B3F8_B547A71B288A_PORT_80_TCP_PROTO=tcp
NEWDEPLOY_FLUSHCACHEDATA_DEFAULT_9ED6_0FCB682DCB38_PORT_80_TCP_PORT=80
NEWDEPLOY_SPEEDAVG_DEFAULT_A11A_277F6DB9BD8C_PORT_80_TCP_ADDR=10.88.10.212
NEWDEPLOY_IOT_WEB_DEFAULT_823C_095E0254CE1B_SERVICE_HOST=10.88.1.35
KUBERNETES_SERVICE_HOST=10.88.0.1
NEWDEPLOY_KP_DEFAULT_B3F8_B547A71B288A_PORT=tcp://10.88.12.81:80
NEWDEPLOY_COUNT_DEFAULT_9909_1BB5447B1F1A_SERVICE_HOST=10.88.2.132
NEWDEPLOY_FLUSHCACHEDATA_DEFAULT_9ED6_0FCB682DCB38_SERVICE_PORT_HTTP_ENV=80
NEWDEPLOY_SPEEDAVG_DEFAULT_A11A_277F6DB9BD8C_SERVICE_PORT=80
NEWDEPLOY_SPEEDAVG_DEFAULT_A11A_277F6DB9BD8C_PORT_80_TCP=tcp://10.88.10.212:80
NEWDEPLOY_DATA_DEFAULT_8A6E_F31F3A19743F_PORT_80_TCP=tcp://10.88.0.4:80
NEWDEPLOY_COUNT_DEFAULT_9909_1BB5447B1F1A_PORT_80_TCP_PROTO=tcp
NEWDEPLOY_FLUSHCACHEDATA_DEFAULT_9ED6_0FCB682DCB38_SERVICE_HOST=10.88.6.1
NEWDEPLOY_SPEEDAVG_DEFAULT_A11A_277F6DB9BD8C_PORT_80_TCP_PROTO=tcp
NEWDEPLOY_SPEEDAVG_DEFAULT_A11A_277F6DB9BD8C_PORT_80_TCP_PORT=80
KUBERNETES_SERVICE_PORT=443
NEWDEPLOY_DATA_DEFAULT_8A6E_F31F3A19743F_PORT=tcp://10.88.0.4:80
NEWDEPLOY_COUNT_DEFAULT_9909_1BB5447B1F1A_SERVICE_PORT=80
NEWDEPLOY_FLUSHCACHEDATA_DEFAULT_9ED6_0FCB682DCB38_PORT_80_TCP_ADDR=10.88.6.1
NEWDEPLOY_FUELAVG_DEFAULT_A34F_D1AF3C3652B2_PORT_80_TCP_PROTO=tcp
NEWDEPLOY_KP_DEFAULT_B3F8_B547A71B288A_SERVICE_PORT_HTTP_ENV=80
NEWDEPLOY_IOTSTATS_DEFAULT_84F0_06A8CCE3B9A2_SERVICE_PORT=80
NEWDEPLOY_FUELAVG_DEFAULT_A34F_D1AF3C3652B2_PORT=tcp://10.88.12.131:80
NEWDEPLOY_KC_DEFAULT_83E3_706C9BF6C12E_SERVICE_HOST=10.88.6.46
NEWDEPLOY_KC_DEFAULT_83E3_706C9BF6C12E_PORT_80_TCP_PROTO=tcp
NEWDEPLOY_KC_DEFAULT_83E3_706C9BF6C12E_PORT_80_TCP_PORT=80
NEWDEPLOY_FLUSHCACHEDATA_DEFAULT_9ED6_0FCB682DCB38_PORT_80_TCP=tcp://10.88.6.1:80
NEWDEPLOY_IOTSTATS_DEFAULT_84F0_06A8CCE3B9A2_PORT_80_TCP=tcp://10.88.0.101:80
NEWDEPLOY_FUELAVG_DEFAULT_A34F_D1AF3C3652B2_SERVICE_PORT_HTTP_ENV=80
NEWDEPLOY_KP_DEFAULT_B3F8_B547A71B288A_SERVICE_PORT=80
NEWDEPLOY_SPEEDAVG_DEFAULT_A11A_277F6DB9BD8C_PORT=tcp://10.88.10.212:80
NEWDEPLOY_IOT_WEB_DEFAULT_823C_095E0254CE1B_PORT_80_TCP_PROTO=tcp
NEWDEPLOY_IOT_WEB_DEFAULT_823C_095E0254CE1B_PORT_80_TCP_ADDR=10.88.1.35
NEWDEPLOY_FUELAVG_DEFAULT_A34F_D1AF3C3652B2_PORT_80_TCP_PORT=80
KUBERNETES_PORT_443_TCP=tcp://10.88.0.1:443
NEWDEPLOY_KP_DEFAULT_B3F8_B547A71B288A_SERVICE_HOST=10.88.12.81
NEWDEPLOY_KP_DEFAULT_B3F8_B547A71B288A_PORT_80_TCP_ADDR=10.88.12.81
NEWDEPLOY_COUNT_DEFAULT_9909_1BB5447B1F1A_SERVICE_PORT_HTTP_ENV=80
NEWDEPLOY_IOTSTATS_DEFAULT_84F0_06A8CCE3B9A2_PORT_80_TCP_PROTO=tcp
NEWDEPLOY_IOTSTATS_DEFAULT_84F0_06A8CCE3B9A2_PORT_80_TCP_PORT=80
NEWDEPLOY_IOT_WEB_DEFAULT_823C_095E0254CE1B_PORT_80_TCP=tcp://10.88.1.35:80
NEWDEPLOY_KC_DEFAULT_83E3_706C9BF6C12E_PORT_80_TCP=tcp://10.88.6.46:80
NEWDEPLOY_COUNT_DEFAULT_9909_1BB5447B1F1A_PORT_80_TCP=tcp://10.88.2.132:80
NEWDEPLOY_FLUSHCACHEDATA_DEFAULT_9ED6_0FCB682DCB38_SERVICE_PORT=80
NEWDEPLOY_SPEEDAVG_DEFAULT_A11A_277F6DB9BD8C_SERVICE_PORT_HTTP_ENV=80
NEWDEPLOY_IOTSTATS_DEFAULT_84F0_06A8CCE3B9A2_SERVICE_PORT_HTTP_ENV=80
NEWDEPLOY_IOTSTATS_DEFAULT_84F0_06A8CCE3B9A2_PORT=tcp://10.88.0.101:80
NEWDEPLOY_DATA_DEFAULT_8A6E_F31F3A19743F_PORT_80_TCP_PORT=80
NEWDEPLOY_KP_DEFAULT_B3F8_B547A71B288A_PORT_80_TCP_PORT=80
NEWDEPLOY_IOTSTATS_DEFAULT_84F0_06A8CCE3B9A2_PORT_80_TCP_ADDR=10.88.0.101
NEWDEPLOY_DATA_DEFAULT_8A6E_F31F3A19743F_SERVICE_HOST=10.88.0.4
NEWDEPLOY_KP_DEFAULT_B3F8_B547A71B288A_PORT_80_TCP=tcp://10.88.12.81:80
NEWDEPLOY_DATA_DEFAULT_8A6E_F31F3A19743F_SERVICE_PORT=80
NEWDEPLOY_KC_DEFAULT_83E3_706C9BF6C12E_PORT_80_TCP_ADDR=10.88.6.46
NEWDEPLOY_COUNT_DEFAULT_9909_1BB5447B1F1A_PORT=tcp://10.88.2.132:80
NEWDEPLOY_COUNT_DEFAULT_9909_1BB5447B1F1A_PORT_80_TCP_PORT=80
NEWDEPLOY_SPEEDAVG_DEFAULT_A11A_277F6DB9BD8C_SERVICE_HOST=10.88.10.212
KUBERNETES_PORT_443_TCP_PROTO=tcp
NEWDEPLOY_DATA_DEFAULT_8A6E_F31F3A19743F_PORT_80_TCP_PROTO=tcp
NEWDEPLOY_FLUSHCACHEDATA_DEFAULT_9ED6_0FCB682DCB38_PORT=tcp://10.88.6.1:80
NEWDEPLOY_FUELAVG_DEFAULT_A34F_D1AF3C3652B2_PORT_80_TCP=tcp://10.88.12.131:80
KUBERNETES_PORT_443_TCP_PORT=443
NEWDEPLOY_KC_DEFAULT_83E3_706C9BF6C12E_PORT=tcp://10.88.6.46:80
NEWDEPLOY_COUNT_DEFAULT_9909_1BB5447B1F1A_PORT_80_TCP_ADDR=10.88.2.132
NEWDEPLOY_IOTSTATS_DEFAULT_84F0_06A8CCE3B9A2_SERVICE_HOST=10.88.0.101
NEWDEPLOY_IOT_WEB_DEFAULT_823C_095E0254CE1B_SERVICE_PORT=80
NEWDEPLOY_IOT_WEB_DEFAULT_823C_095E0254CE1B_PORT=tcp://10.88.1.35:80
KUBERNETES_PORT=tcp://10.88.0.1:443
NEWDEPLOY_DATA_DEFAULT_8A6E_F31F3A19743F_SERVICE_PORT_HTTP_ENV=80
NEWDEPLOY_KC_DEFAULT_83E3_706C9BF6C12E_SERVICE_PORT=80
NEWDEPLOY_FLUSHCACHEDATA_DEFAULT_9ED6_0FCB682DCB38_PORT_80_TCP_PROTO=tcp
NEWDEPLOY_IOT_WEB_DEFAULT_823C_095E0254CE1B_SERVICE_PORT_HTTP_ENV=80
NEWDEPLOY_IOT_WEB_DEFAULT_823C_095E0254CE1B_PORT_80_TCP_PORT=80
HOME=/root
```

Then I defined the podspec with `enableServiceLinks` attribute as seen in the pod spec for environment below:

```
apiVersion: fission.io/v1
kind: Environment
metadata:
  creationTimestamp: null
  name: python
  namespace: default
spec:
  TerminationGracePeriod: 5
  builder:
    command: build
    image: fission/python-builder
  keeparchive: false
  poolsize: 3
  resources: {}
  runtime:
    functionendpointport: 0
    image: fission/python-env
    loadendpointpath: ""
    loadendpointport: 0
    podspec:
      enableServiceLinks: false
  version: 2
```

And that reduces the number to bare minimum Kubernetes related environment vars:

```
kex -it $ff poolmgr-python-default-16031911-7c4fccc9fd-98ffq -c python -- printenv
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=poolmgr-python-default-16031911-7c4fccc9fd-98ffq
TERM=xterm
KUBERNETES_SERVICE_HOST=10.88.0.1
KUBERNETES_SERVICE_PORT=443
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_PORT=tcp://10.88.0.1:443
KUBERNETES_PORT_443_TCP=tcp://10.88.0.1:443
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP_ADDR=10.88.0.1
HOME=/root
```

**Comment by vishal-biyani** [comment]
Thank you so much again @darkworon

**Pull request merged**
