### PR TITLE
Fix Fission cli can be more like k8s.

### PR DESCRIPTION
**Pull request by tosone**
Before we can delete function like this `fission fn delete --name func-name`, but now we can operate this action with command `fission fn delete func-name`, can be more like k8s.

### CODE REVIEW

**Comment by vishal-biyani** [comment]
Hi @tosone Will this be backward compatible - as in if we pass the name even then it works? Also wanted to confirm if we are only changing the delete part of CLI right?

**Comment by tosone** [comment]
Emmm, this pr not backward compatible. Can't be compatible in both ways, because the `function name` is a required parameter.

**Comment by vishal-biyani** [comment]
@tosone In the interest of backward compatibility - are you ok if we don't merge this change? Sorry but want to ensure that other users don't get affected.

**Comment by tosone** [comment]
It is ok to reject this pr. Made this during reading the source code.

Thank you for your reply.

**Comment by tosone** [comment]
Just close this PR.

**Pull request closed without merging**
