### PR TITLE
solve kubernetes/client-go nested vendor

### PR DESCRIPTION
**Pull request by yesqiao**
More details in [https://github.com/kubernetes/client-go/blob/master/INSTALL.md#glide](url)

---
This change is [Reviewable](https://reviewable.io/reviews/fission/fission/1048)

### CODE REVIEW

**Comment by erwinvaneyk** [comment]
LGTM 👍

**Comment by vishal-biyani** [comment]
@yesqiao Can you please rebase once so we can merge.

**Comment by yesqiao** [comment]
> @yesqiao Can you please rebase once so we can merge.

I haven't found rebase button on web page. Wheather I should rebase fission/fission master on my forked repo, then make a new pr. Is it right?

**Comment by soamvasani** [comment]
Thanks @yesqiao !

**Pull request merged**
