### PR TITLE
Delete namespace in background to reduce build time

### PR DESCRIPTION
**Pull request by life1347**
This change is [Reviewable](https://reviewable.io/reviews/fission/fission/791)

### CODE REVIEW

**Comment by erwinvaneyk** [comment]
I had a similar issue with Workflows --- do you ensure that subsequent tests are not affected by 'still deleting' namespaces?

**Comment by life1347** [comment]
Yes, it won't affect following tests since the deleted namespace are only used in this test script.
And this PR is more like a workaround for now to reduce the job time lower than 50mins cause I noticed some of the build was failed due to exceeded time limitation. 
```
https://travis-ci.org/fission/fission/builds/402665319
The job exceeded the maximum time limit for jobs, and has been terminated.
```
We need to find out some ways to lower job time in future.

**Comment by soamvasani** [comment]
Does this work?  Does the travis worker wait for background jobs to finish?

**Comment by life1347** [comment]
Yes, it works. The build time is lower than previous about 8mins. (49 -> 41).
I think Travis worker won't wait for the background process, but the deletion will be finished before the end of the whole build process.

**Pull request merged**
