### PR TITLE
Fscache support for multiple kubernetes objects

### PR DESCRIPTION
**Pull request by vishal-biyani**
Addresses #415

In poolmgr backend fsvc could store only one Kubernetes object, but newdeploy backend created three objects for a function (Deployment, Service, HPA). This PR adds support for storing multiple Kube objects in FuncSvc. As a side effect, the DeleteByKubeObject does not work very well so this PR also adds a new DeleteOld implementation and changes the ListOld implementation a bit. Finally all these changes impact the generic pools idlePodRepaer hence that has been changed.

---
This change is [Reviewable](https://reviewable.io/reviews/fission/fission/435)

### CODE REVIEW

**Comment by soamvasani** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[executor/fscache/functionServiceCache.go, line 178 at r1](https://reviewable.io:443/reviews/fission/fission/435#-L2v6MnLG6kVFdGHzNZR:-L2v6MnM54cmni0LJSvJ:bg0bpbx) ([raw file](https://github.com/fission/fission/blob/94f9375e1c2b8a86f3a111a677302b0cc95c00d7/executor/fscache/functionServiceCache.go#L178)):*
> ```Go
> 	}
> 	for _, kubeObj := range fsvc.KubernetesObjects {
> 		err, _ := fsc.byKubeObject.Set(kubeObj, *fsvc.Function)
> ```

Do we still need `byKubeObject`?  Where is it used now that `DeleteByKubeObject` is gone?  If it is not used any more we should just remove it.

---

*[executor/poolmgr/gp.go, line 583 at r1](https://reviewable.io:443/reviews/fission/fission/435#-L2v6jZ6FyrE0x98xs5C:-L2v6jZ6FyrE0x98xs5D:bbm81td) ([raw file](https://github.com/fission/fission/blob/94f9375e1c2b8a86f3a111a677302b0cc95c00d7/executor/poolmgr/gp.go#L583)):*
> ```Go
> 	}
> 
> 	kubeObjRef := []api.ObjectReference{
> ```

minor nit, can you change this to `kubeObjRefs`

---

*[executor/poolmgr/gp.go, line 623 at r1](https://reviewable.io:443/reviews/fission/fission/435#-L2v6xL3VpUf51SgHHhB:-L2v6xL3VpUf51SgHHhC:b-t1vigw) ([raw file](https://github.com/fission/fission/blob/94f9375e1c2b8a86f3a111a677302b0cc95c00d7/executor/poolmgr/gp.go#L623)):*
> ```Go
> 	}
> 
> 	var pod *apiv1.Pod
> ```

do you need to declare pod here?  you could just use `:=` below, right?

---

*[executor/poolmgr/gp.go, line 656 at r1](https://reviewable.io:443/reviews/fission/fission/435#-L2v944Dz53hqiVPgm3-:-L2v944Dz53hqiVPgm30:brbymdy) ([raw file](https://github.com/fission/fission/blob/94f9375e1c2b8a86f3a111a677302b0cc95c00d7/executor/poolmgr/gp.go#L656)):*
> ```Go
> 	for {
> 		time.Sleep(time.Minute)
> 		objects, err := gp.fsCache.ListOld(&gp.env.Metadata, gp.idlePodReapTime)
> ```

these aren't k8s objects any more, can you name this something else (like `funcSvcs`)

---

*[executor/poolmgr/gp.go, line 664 at r1](https://reviewable.io:443/reviews/fission/fission/435#-L2v7ALyyy_6eNErgGF1:-L2v7ALyyy_6eNErgGF2:b-viv2qs) ([raw file](https://github.com/fission/fission/blob/94f9375e1c2b8a86f3a111a677302b0cc95c00d7/executor/poolmgr/gp.go#L664)):*
> ```Go
> 			err := gp.CleanupFunctionService(obj)
> 			if err != nil {
> 				log.Printf("Error deleting Kube objects for fsvc '%v': %v", obj, err)
> ```

`obj` is no longer a Kubernetes object... could you log the kind,namespace, and name for each k8s object referenced in the list? (also, really minor nit: please use the full word `Kubernetes` in publicly visible messages including logs)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fission/fission/435)*

**Comment by vishal-biyani** [comment]
Review status: 1 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[executor/fscache/functionServiceCache.go, line 178 at r1](https://reviewable.io:443/reviews/fission/fission/435#-L2v6MnLG6kVFdGHzNZR:-L2ylqwY0Vd5-WAQz2Hf:b8fyw5v) ([raw file](https://github.com/fission/fission/blob/94f9375e1c2b8a86f3a111a677302b0cc95c00d7/executor/fscache/functionServiceCache.go#L178)):*
<details><summary><i>Previously, soamvasani (Soam Vasani) wrote…</i></summary><blockquote>

Do we still need `byKubeObject`?  Where is it used now that `DeleteByKubeObject` is gone?  If it is not used any more we should just remove it.
</blockquote></details>

That's a good point Soam. I fixed the whole cache so that now there is no `byKubeObject` anywhere.

---

*[executor/poolmgr/gp.go, line 583 at r1](https://reviewable.io:443/reviews/fission/fission/435#-L2v6jZ6FyrE0x98xs5C:-L2yFNNtjF3MivZRnKox:b-896fix) ([raw file](https://github.com/fission/fission/blob/94f9375e1c2b8a86f3a111a677302b0cc95c00d7/executor/poolmgr/gp.go#L583)):*
<details><summary><i>Previously, soamvasani (Soam Vasani) wrote…</i></summary><blockquote>

minor nit, can you change this to `kubeObjRefs`
</blockquote></details>

Done.

---

*[executor/poolmgr/gp.go, line 623 at r1](https://reviewable.io:443/reviews/fission/fission/435#-L2v6xL3VpUf51SgHHhB:-L2yFWb5A0RqPHRZnY64:b-896fix) ([raw file](https://github.com/fission/fission/blob/94f9375e1c2b8a86f3a111a677302b0cc95c00d7/executor/poolmgr/gp.go#L623)):*
<details><summary><i>Previously, soamvasani (Soam Vasani) wrote…</i></summary><blockquote>

do you need to declare pod here?  you could just use `:=` below, right?
</blockquote></details>

Done.

---

*[executor/poolmgr/gp.go, line 656 at r1](https://reviewable.io:443/reviews/fission/fission/435#-L2v944Dz53hqiVPgm3-:-L2yLda6o3HLmpmrgSxl:b-896fix) ([raw file](https://github.com/fission/fission/blob/94f9375e1c2b8a86f3a111a677302b0cc95c00d7/executor/poolmgr/gp.go#L656)):*
<details><summary><i>Previously, soamvasani (Soam Vasani) wrote…</i></summary><blockquote>

these aren't k8s objects any more, can you name this something else (like `funcSvcs`)
</blockquote></details>

Done.

---

*[executor/poolmgr/gp.go, line 664 at r1](https://reviewable.io:443/reviews/fission/fission/435#-L2v7ALyyy_6eNErgGF1:-L2ySJDNaz-D1JSQXeHD:b-896fix) ([raw file](https://github.com/fission/fission/blob/94f9375e1c2b8a86f3a111a677302b0cc95c00d7/executor/poolmgr/gp.go#L664)):*
<details><summary><i>Previously, soamvasani (Soam Vasani) wrote…</i></summary><blockquote>

`obj` is no longer a Kubernetes object... could you log the kind,namespace, and name for each k8s object referenced in the list? (also, really minor nit: please use the full word `Kubernetes` in publicly visible messages including logs)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fission/fission/435)*

**Comment by soamvasani** [comment]
tests passed, just needs gofmt:
```
!!! 'gofmt -s' needs to be run on the following files: 
./executor/fscache/functionServiceCache.go
./executor/poolmgr/gp.go
```

**Comment by vishal-biyani** [comment]
This PR introduces a change in the cache structure. Earlier, the struct `FunctionServiceCache` had three caches - `byFunction`, `byAddress` and `byKubeObject`. Also, the deletion was operated by Kubernetes object using method `DeleteByKubeObject`. 

The new implementation does away with the `byKubeObject` completely and the deletion mechanism simply calls `DeleteOld`. This simplifies cache relatively and also make it suitable for use by `newDeploy` backend.

**Comment by soamvasani** [comment]
LGTM

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fission/fission/435#-:-L3-m35Ma1QBffWKgOZx:bb6ywmx)*

**Pull request merged**
