### PR TITLE
fix: update vunerable nodejs deps, add gitignore

### LINKED ISSUE #1222: Update nodejs environment vulnerable dependencies
The Issue to track #1220 #1221 . The dependencies (`request-promise-native`, `underscore`) mentioned in PRs above do not ship any new releases yet. So open this issue for future tracking.

### PR DESCRIPTION
**Pull request by WilliamHYZhang**
Closes #1222 

- Updates nodejs vunerable dependencies (all of which that are outdated)
- Adds `.gitignore` file in the `examples/nodejs` subfolder for `node_modules/`

---
This change is [Reviewable](https://reviewable.io/reviews/fission/fission/1802)

### CODE REVIEW

**Comment by vishal-biyani** [comment]
Hey @WilliamHYZhang Should we not just update `package.json` instead of committing `package-lock.json`?

**Comment by WilliamHYZhang** [comment]
Yeah, you're right, will do today.

**Comment by WilliamHYZhang** [comment]
Hi @vishal-biyani I added the `package.json` files.

**Comment by vishal-biyani** [comment]
Hi @WilliamHYZhang I still see package-lock.json which are not needed:
image

**Comment by WilliamHYZhang** [comment]
@vishal-biyani sorry about that, those are removed now.

**Comment by therahulbhati** [comment]
@WilliamHYZhang We are moving environments in a new repo. Can you please raise a PR against https://github.com/fission/environments and close this.

**Comment by vishal-biyani** [comment]
As environments have moved to fission/environments, closing this one.

**Pull request closed without merging**
