### PR TITLE
Add support for setting nodeSelector/affinity/tolerations on all depl…

### PR DESCRIPTION
**Pull request by davidsmf**
A simple solution to #1155 all of the deployments will have the same affinity etc.

---
This change is [Reviewable](https://reviewable.io/reviews/fission/fission/1156)

### CODE REVIEW

**Comment by life1347** [comment]
Hi @davidsmf , thanks for the PR.

Helm failed due to there is no variable definition in values.yaml

```
Error: render error in "fission-all/templates/deployment.yaml": template: fission-all/templates/deployment.yaml:166:14: executing "fission-all/templates/deployment.yaml" at <.Values.controller.n...>: can't evaluate field nodeSelector in type interface {}
```

And since for most users don't need to use affinity, here are some suggestions to address the problem

1. Adding the following config to `values.yaml` (change `controller` to `coreComponmentPodConfig`)

```
#coreComponmentPodConfig:
#  affinity:
#  tolerations:
#  nodeSelector:
```

2. Add some comment to explain the setting would be very helpful for users. Then users will know what the setting is for and uncomment setting when needed.
3. Add example setting for user to follow with

For the `render error` problem, you can check the `coreComponmentPodConfig` exists first so that helm won't break even the variables are not existing.

```
{{- if .Values.coreComponmentPodConfig }}
  {{- if .Values.coreComponmentPodConfig.nodeSelector }}
  ......
{{- end}}
```

**Comment by soamvasani** [comment]
@davidsmf thanks for the PR!  Will you be addressing @life1347 's comments?  Please let us know if you have any questions.

**Comment by davidsmf** [comment]
Sorry, been busy with a newborn, I should be able to address them, but not
for a couple of weeks.

David

**Comment by soamvasani** [comment]
Congrats on the newborn :smile: :baby:

**Comment by life1347** [comment]
After #1170 we are able to set affinity on all core components. Close this one.
Still thanks for all your contribution and congrats on the newborn 🎉

**Pull request closed without merging**
