### PR TITLE
[WIP] Add rabbitmq integration in mq trigger

### LINKED ISSUE #198: Function triggers for RabbitMQ / AMQP

### PR DESCRIPTION
**Pull request by viveksinghggits**
This fixes #198

If there are already some messages in the queue and we create the mqt later the configured function will be called for the message that were present in the queue already as well.

We are not able to unsubscribe to the rabbitmq yet, so even if we delete the mqt the function gets called.

---
This change is [Reviewable](https://reviewable.io/reviews/fission/fission/1478)

### CODE REVIEW

**Comment by life1347** [comment]
hey, any updates?

**Comment by viveksinghggits** [comment]
Hi @life1347 
I have been a bit busy, I will make the changes tomorrow maybe.

**Comment by ajoslin103** [comment]
I would be so happy if I could use RMQ to trigger

**Comment by viveksinghggits** [comment]
@ajoslin103 let me see,  If I can look into this again.

**Comment by ajoslin103** [comment]
Hi @viveksinghggits 
Thank you! I am very grateful for your time.  I am describing my use-case in #1561

**Comment by viveksinghggits** [comment]
Hey @ajoslin103 
So it seems we are considering another way to implement this. And the discussion is going on under 
https://github.com/fission/fission/issues/1565

**Comment by ajoslin103** [comment]
Thanks!  I'll follow along over there.

**Comment by vishal-biyani** [comment]
I Will close this PR for now as the PR https://github.com/fission/fission/pull/1621 plans to enable Fission <> Keda <> RabbitMQ integration. If needed in the future, we can revisit. Thanks for your efforts @viveksinghggits

**Comment by therahulbhati** [comment]
Hi @ajoslin103, currently I am working on writing [keda connector](https://github.com/fission/fission/issues/1663). Can you please let us know what protocol(http/s or amqp) do you use to connect to Rabbitmq, so that we can prioritize that in the upcoming release.

**Pull request closed without merging**
