### PR TITLE
Added labels to flags '--url', '--prefix', '--method' to reflect thei…

### PR DESCRIPTION
**Pull request by nickmancari**
…r deprecation for the 'fn create' use case.

### CODE REVIEW

**Comment by sanketsudake** [comment]
@nickmancari Can you please rebase branch with latest master ?

**Review by sanketsudake — APPROVED** [review]
LGTM for 1.15 release, in upcoming release we would remove corresponding options from `fn create` command.

**Comment by nickmancari** [comment]
> @nickmancari Can you please rebase branch with latest master ?

Done

**Comment by sanketsudake** [comment]
Thanks for the PR @nickmancari 🎉

**Pull request merged**
