### PR TITLE
support for providing multiple CMs and secrets in fn create

### PR DESCRIPTION
**Pull request by viveksinghggits**
This change fixes the issue #1055 .

---
This change is [Reviewable](https://reviewable.io/reviews/fission/fission/1282)

### CODE REVIEW

**Comment by life1347** [comment]
@viveksinghggits Thanks for the PR. Would you mind adding test to `test/tests/test_secret_cfgmap` to test against with the changes?

**Comment by viveksinghggits** [comment]
> @viveksinghggits Thanks for the PR. Would you mind adding test to `test/tests/test_secret_cfgmap` to test against with the changes?

@life1347 I will add the tests and update.

**Comment by viveksinghggits** [comment]
hi @life1347 
to write the test cases I was thinking of creating another template .py file that will read the two provided configmaps/secrets and then have a separate function (line `checkFunctionResponse`) that will call above function to check if two configmaps/secrets are being returned or not.
My concern was if I should created another function like `checkFunctionResponse` or not.
cc @vishal-biyani

**Comment by life1347** [comment]
How about writing a fission function that combines multiple value of confimaps/secret into one line response and then use `checkFunctionResponse` to check the response body. In this way, you don't need to write additional bash function.

**Comment by viveksinghggits** [comment]
Hi @life1347 
that sounds good to me, I will make the changes and update.

**Comment by viveksinghggits** [comment]
@life1347 
can we get this merged.

**Comment by life1347** [comment]
@viveksinghggits yes, I will get this merged today.

**Comment by life1347** [comment]
LGTM & CI integration build passed: https://travis-ci.org/fission/fission/builds/578692761

**Comment by life1347** [comment]
@viveksinghggits would you mind updating fission doc for multiple CMs & secrets access?

**Comment by viveksinghggits** [comment]
Hi @life1347 
I should have done that, forgot I think. Will do that and update.

**Comment by viveksinghggits** [comment]
Hi @life1347 
I have update the document and raised PR
https://github.com/fission/docs.fission.io/pull/161

**Pull request merged**
