### PR TITLE
Improve error message if an older CLI attempts to make a request

### PR DESCRIPTION
**Pull request by rapitable**
Tested using both v1 and v2 CLIs against v2 server

### CODE REVIEW

**Comment by soamvasani** [comment]
Thanks, this is great!

**Comment by rapitable** [comment]
You're welcome. This is my very first PR, OSS contribution, and Go code :-)

**Comment by soamvasani** [comment]
@rapitable Wow! That's so great to hear :) Welcome to the community :)

**Comment by rapitable** [comment]
Thanks! It's great what you're doing with this project. Look forward to working together :-)

**Pull request merged**
